/**
 * 层依赖存量基线（棘轮）—— 由 `bun scripts/check-layer-deps.ts --update` 生成，勿手改。
 *
 * `"<from> -> <to>"` → 允许存在该层对违规的仓库相对文件清单。
 * 只减不增；新文件出现违规即失败（oxlint `freeanima/layer-deps` 与
 * `scripts/check-layer-deps.ts` 共用本表）。
 */
export const LAYER_DEPS_BASELINE: Readonly<Record<string, readonly string[]>> = {
  "app-frame -> core": [
    "packages/frontend/client/app-frame/spa/settings/habitat-config/llm-settings-draft.ts",
    "packages/frontend/client/app-frame/spa/settings/habitat-config/llm-settings-forms.tsx",
  ],
  "capabilities -> features": [
    "packages/capabilities/connectors/email/idle.ts",
    "packages/capabilities/connectors/email/imap-client.ts",
    "packages/capabilities/connectors/email/index.ts",
    "packages/capabilities/connectors/email/mailbox-ops.ts",
    "packages/capabilities/connectors/email/new-mail-notify.test.ts",
    "packages/capabilities/connectors/email/new-mail-notify.ts",
    "packages/capabilities/connectors/email/password.ts",
    "packages/capabilities/connectors/email/send.ts",
    "packages/capabilities/connectors/email/sent-copy.ts",
    "packages/capabilities/connectors/email/sync.ts",
    "packages/capabilities/connectors/vault/agent-secrets.ts",
    "packages/capabilities/connectors/vault/user-secrets.ts",
    "packages/capabilities/federation/hub-ws-server.ts",
    "packages/capabilities/federation/satellite-client.ts",
    "packages/capabilities/outpost/transport/ws-server.ts",
    "packages/capabilities/tools/media/tools.ts",
    "packages/capabilities/tools/subprocess-secrets.ts",
  ],
  "capabilities -> server": [
    "packages/capabilities/connectors/cron/deliver.ts",
    "packages/capabilities/connectors/cron/handle-manager.ts",
    "packages/capabilities/connectors/cron/inprocess-builtins.test.ts",
    "packages/capabilities/connectors/cron/inprocess-builtins.ts",
    "packages/capabilities/connectors/cron/module.ts",
    "packages/capabilities/connectors/cron/paths.ts",
    "packages/capabilities/connectors/cron/runner.ts",
    "packages/capabilities/connectors/email/password.ts",
    "packages/capabilities/connectors/gateway/cron-deliver.ts",
    "packages/capabilities/connectors/gateway/discord/discord-adapter.ts",
    "packages/capabilities/connectors/gateway/discord/discord-clarify-pending.ts",
    "packages/capabilities/connectors/gateway/discord/discord-retry.ts",
    "packages/capabilities/connectors/gateway/discord/discord-slash.ts",
    "packages/capabilities/connectors/gateway/platforms.ts",
    "packages/capabilities/connectors/gateway/stream-state/types.ts",
    "packages/capabilities/connectors/gateway/weixin/weixin-adapter.ts",
    "packages/capabilities/connectors/gateway/weixin/weixin-credentials.ts",
    "packages/capabilities/mcp-client/mcp-status.test.ts",
    "packages/capabilities/outpost/transport/bun-route.ts",
    "packages/capabilities/outpost/transport/stream-bridge.ts",
    "packages/capabilities/outpost/transport/types.ts",
    "packages/capabilities/outpost/transport/ws-server.ts",
    "packages/capabilities/tools/browser-tools.test.ts",
    "packages/capabilities/tools/execute-code.test.ts",
    "packages/capabilities/tools/file-tools.test.ts",
    "packages/capabilities/tools/local-tools.test.ts",
    "packages/capabilities/tools/slash-commands/builtins.ts",
  ],
  "core -> capabilities": [
    "packages/core/llm/auto-llm-prompt.test.ts",
    "packages/core/llm/llm-messages.test.ts",
    "packages/core/llm/llm-stack.test.ts",
    "packages/core/llm/tool-loop-integrity.test.ts",
    "packages/core/schemas/cross-package-schemas.test.ts",
  ],
  "features -> portal-sdk": [
    "packages/features/companion/server/config.ts",
    "packages/features/companion/server/habitat-sync.ts",
  ],
  "features -> server": [
    "packages/features/bookmark/cordis-plugin.ts",
    "packages/features/calendar/cordis-plugin.ts",
    "packages/features/calendar/domain/convert-task-event.ts",
    "packages/features/chat/cordis-plugin.ts",
    "packages/features/chat/habitat/routes/index.ts",
    "packages/features/coding/cordis-plugin.ts",
    "packages/features/companion/cordis-plugin.ts",
    "packages/features/companion/domain/config.ts",
    "packages/features/contact/cordis-plugin.ts",
    "packages/features/diary/cordis-plugin.ts",
    "packages/features/email/cordis-plugin.ts",
    "packages/features/email/domain/attach-task.ts",
    "packages/features/entity/cordis-plugin.ts",
    "packages/features/federation/cordis-plugin.ts",
    "packages/features/habit/cordis-plugin.ts",
    "packages/features/habitat/cordis-plugin.ts",
    "packages/features/habitat/habitat/asr-handler.ts",
    "packages/features/habitat/habitat/habitat-api/api/constants.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/config-test-connection.test.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/config-test-connection.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/config.test.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/config.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/entities.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/runtime.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/service-api-tokens.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/skills.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/status.ts",
    "packages/features/habitat/habitat/habitat-api/handlers/tls-ca.ts",
    "packages/features/habitat/habitat/habitat-api/http-shutdown.ts",
    "packages/features/habitat/habitat/habitat-api/server.ts",
    "packages/features/habitat/habitat/habitat-api/service-auth.ts",
    "packages/features/habitat/habitat/habitat-api/service-restart.ts",
    "packages/features/habitat/habitat/habitat-api/tls-ca-auth.test.ts",
    "packages/features/habitat/habitat/routes/index.ts",
    "packages/features/habitat/habitat/tts-handler.test.ts",
    "packages/features/habitat/habitat/tts-handler.ts",
    "packages/features/health/cordis-plugin.ts",
    "packages/features/mcp/cordis-plugin.ts",
    "packages/features/note/cordis-plugin.ts",
    "packages/features/notification/cordis-plugin.ts",
    "packages/features/notification/habitat/runtime-deps.ts",
    "packages/features/object-storage/cordis-plugin.ts",
    "packages/features/object-storage/domain/bun-s3.ts",
    "packages/features/objective/cordis-plugin.ts",
    "packages/features/pomodoro/cordis-plugin.ts",
    "packages/features/project/cordis-plugin.ts",
    "packages/features/room/cordis-plugin.ts",
    "packages/features/shell-quick/cordis-plugin.ts",
    "packages/features/subagent/cordis-plugin.ts",
    "packages/features/subagent/domain/subagent-tools.ts",
    "packages/features/tag/cordis-plugin.ts",
    "packages/features/task/cordis-plugin.ts",
    "packages/features/task/domain/item-store.ts",
    "packages/features/task/habitat/advance-reminder-stream.ts",
    "packages/features/vault/cordis-plugin.ts",
    "packages/features/workflow/domain/runner.ts",
    "packages/features/workflow/domain/workflow-tools.ts",
  ],
  "portal -> core": ["packages/frontend/portal/vite-config-cross-pkg.ts"],
  "portal-sdk -> core": ["packages/frontend/client/portal-sdk/speech/edge-voices.ts"],
  "portal-sdk -> portal": ["packages/frontend/client/portal-sdk/pomodoro-active.ts"],
  "ui-features -> app-frame": [
    "packages/frontend/features/coding/build.ts",
    "packages/frontend/features/coding/vite.config.ts",
    "packages/frontend/features/companion/build.ts",
    "packages/frontend/features/companion/vite.config.ts",
    "packages/frontend/features/pomodoro/build-float.ts",
    "packages/frontend/features/pomodoro/vite.float.config.ts",
  ],
  "ui-features -> features": [
    "packages/frontend/features/habitat/ui/habitat/lib/api.ts",
    "packages/frontend/features/habitat/ui/habitat/lib/format-datetime.ts",
    "packages/frontend/features/habitat/ui/habitat/routes/_sidebar/self-layer.tsx",
    "packages/frontend/features/habitat/ui/habitat/routes/_sidebar/system-prompt.tsx",
    "packages/frontend/features/habitat/ui/habitat/routes/_sidebar/tools.tsx",
  ],
  "ui-features -> portal": [
    "packages/frontend/features/coding/ui/spa/main.tsx",
    "packages/frontend/features/companion/ui/spa/main.tsx",
    "packages/frontend/features/pomodoro/ui/float/main.tsx",
  ],
  "ui-kit -> portal-sdk": [
    "packages/frontend/ui-kit/composite/EntityIdLabel.tsx",
    "packages/frontend/ui-kit/lib/task-list-tree.ts",
  ],
};
