/**
 * 层依赖存量基线（棘轮）—— 由 `bun scripts/check-layer-deps.ts --update` 生成，勿手改。
 *
 * `"<from> -> <to>"` → 允许存在该层对违规的仓库相对文件清单。
 * 只减不增；新文件出现违规即失败（oxlint `freeanima/layer-deps` 与
 * `scripts/check-layer-deps.ts` 共用本表）。
 */
export const LAYER_DEPS_BASELINE: Readonly<Record<string, readonly string[]>> = {
  "app-frame -> core": [
    "packages/frontend/client/app-frame/spa/settings/habitat-config/llm-settings-draft.ts",
    "packages/frontend/client/app-frame/spa/settings/habitat-config/llm-settings-forms.tsx",
  ],
  "capabilities -> features": [
    "packages/habitat/capabilities/connectors/email/idle.ts",
    "packages/habitat/capabilities/connectors/email/imap-client.ts",
    "packages/habitat/capabilities/connectors/email/index.ts",
    "packages/habitat/capabilities/connectors/email/mailbox-ops.ts",
    "packages/habitat/capabilities/connectors/email/new-mail-notify.test.ts",
    "packages/habitat/capabilities/connectors/email/new-mail-notify.ts",
    "packages/habitat/capabilities/connectors/email/password.ts",
    "packages/habitat/capabilities/connectors/email/send.ts",
    "packages/habitat/capabilities/connectors/email/sent-copy.ts",
    "packages/habitat/capabilities/connectors/email/sync.ts",
    "packages/habitat/capabilities/connectors/vault/agent-secrets.ts",
    "packages/habitat/capabilities/connectors/vault/user-secrets.ts",
    "packages/habitat/capabilities/federation/hub-ws-server.ts",
    "packages/habitat/capabilities/federation/satellite-client.ts",
    "packages/habitat/capabilities/outpost/transport/ws-server.ts",
    "packages/habitat/capabilities/tools/media/tools.ts",
    "packages/habitat/capabilities/tools/subprocess-secrets.ts",
  ],
  "capabilities -> server": [
    "packages/habitat/capabilities/connectors/cron/deliver.ts",
    "packages/habitat/capabilities/connectors/cron/handle-manager.ts",
    "packages/habitat/capabilities/connectors/cron/inprocess-builtins.test.ts",
    "packages/habitat/capabilities/connectors/cron/inprocess-builtins.ts",
    "packages/habitat/capabilities/connectors/cron/module.ts",
    "packages/habitat/capabilities/connectors/cron/paths.ts",
    "packages/habitat/capabilities/connectors/cron/runner.ts",
    "packages/habitat/capabilities/connectors/email/password.ts",
    "packages/habitat/capabilities/connectors/gateway/cron-deliver.ts",
    "packages/habitat/capabilities/connectors/gateway/discord/discord-adapter.ts",
    "packages/habitat/capabilities/connectors/gateway/discord/discord-clarify-pending.ts",
    "packages/habitat/capabilities/connectors/gateway/discord/discord-retry.ts",
    "packages/habitat/capabilities/connectors/gateway/discord/discord-slash.ts",
    "packages/habitat/capabilities/connectors/gateway/platforms.ts",
    "packages/habitat/capabilities/connectors/gateway/stream-state/types.ts",
    "packages/habitat/capabilities/connectors/gateway/weixin/weixin-adapter.ts",
    "packages/habitat/capabilities/connectors/gateway/weixin/weixin-credentials.ts",
    "packages/habitat/capabilities/connectors/vault/user-secrets.ts",
    "packages/habitat/capabilities/federation/hub-runtime-context.ts",
    "packages/habitat/capabilities/federation/runtime-context.ts",
    "packages/habitat/capabilities/federation/satellite-rpc.ts",
    "packages/habitat/capabilities/mcp-client/mcp-status.test.ts",
    "packages/habitat/capabilities/memory/service/reflect.ts",
    "packages/habitat/capabilities/memory/service/retain-engine-port.ts",
    "packages/habitat/capabilities/outpost/transport/bun-route.ts",
    "packages/habitat/capabilities/outpost/transport/runtime-context.ts",
    "packages/habitat/capabilities/outpost/transport/stream-bridge.ts",
    "packages/habitat/capabilities/outpost/transport/types.ts",
    "packages/habitat/capabilities/outpost/transport/ws-server.ts",
    "packages/habitat/capabilities/tools/browser-camofox.ts",
    "packages/habitat/capabilities/tools/browser-tools.test.ts",
    "packages/habitat/capabilities/tools/clarify/clarify.ts",
    "packages/habitat/capabilities/tools/docs-corpus.ts",
    "packages/habitat/capabilities/tools/execute-code.test.ts",
    "packages/habitat/capabilities/tools/file-tools.test.ts",
    "packages/habitat/capabilities/tools/local-tools.test.ts",
    "packages/habitat/capabilities/tools/notification/port.ts",
    "packages/habitat/capabilities/tools/slash-commands/builtins.ts",
    "packages/habitat/capabilities/tools/web.ts",
  ],
  "core -> capabilities": [
    "packages/habitat/core/llm/auto-llm-prompt.test.ts",
    "packages/habitat/core/llm/llm-messages.test.ts",
    "packages/habitat/core/llm/llm-stack.test.ts",
    "packages/habitat/core/llm/tool-loop-integrity.test.ts",
    "packages/habitat/core/schemas/cross-package-schemas.test.ts",
  ],
  "core -> server": [
    "packages/habitat/core/compress/compression-summary-scheduler.ts",
    "packages/habitat/core/config/capability-injection.ts",
    "packages/habitat/core/db/pg/client.ts",
    "packages/habitat/core/db/pg/embedding/runtime.ts",
    "packages/habitat/core/db/pg/search/runtime.ts",
    "packages/habitat/core/hooks/prompt/runner.test.ts",
    "packages/habitat/core/hooks/prompt/runner.ts",
    "packages/habitat/core/llm/llm-stack-configurator.ts",
    "packages/habitat/core/llm/llm-stack-runtime.ts",
    "packages/habitat/core/llm/llm-stack.test.ts",
    "packages/habitat/core/redis/client.ts",
    "packages/habitat/core/skill/content.ts",
    "packages/habitat/core/skill/project-overlay.ts",
    "packages/habitat/core/soft-failure/notify.ts",
    "packages/habitat/core/tokenizer/resolve-context.ts",
    "packages/habitat/core/tool/conversation-tools.test.ts",
    "packages/habitat/core/tool/default-conversation-toolsets.test.ts",
    "packages/habitat/core/tool/policy-port.ts",
  ],
  "features -> portal-sdk": [
    "packages/habitat/features/companion/server/config.ts",
    "packages/habitat/features/companion/server/habitat-sync.ts",
  ],
  "features -> server": [
    "packages/habitat/features/bookmark/cordis-plugin.ts",
    "packages/habitat/features/calendar/cordis-plugin.ts",
    "packages/habitat/features/calendar/domain/convert-task-event.ts",
    "packages/habitat/features/chat/cordis-plugin.ts",
    "packages/habitat/features/chat/habitat/routes/index.ts",
    "packages/habitat/features/coding/cordis-plugin.ts",
    "packages/habitat/features/companion/cordis-plugin.ts",
    "packages/habitat/features/companion/domain/config.ts",
    "packages/habitat/features/contact/cordis-plugin.ts",
    "packages/habitat/features/diary/cordis-plugin.ts",
    "packages/habitat/features/email/cordis-plugin.ts",
    "packages/habitat/features/email/domain/attach-task.ts",
    "packages/habitat/features/email/domain/sync-port.ts",
    "packages/habitat/features/entity/cordis-plugin.ts",
    "packages/habitat/features/federation/cordis-plugin.ts",
    "packages/habitat/features/habit/cordis-plugin.ts",
    "packages/habitat/features/habitat/cordis-plugin.ts",
    "packages/habitat/features/habitat/habitat/asr-handler.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/api/constants.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/config-test-connection.test.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/config-test-connection.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/config.test.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/config.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/entities.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/runtime.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/service-api-tokens.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/skills.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/status.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/handlers/tls-ca.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/http-shutdown.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/server.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/service-auth.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/service-restart.ts",
    "packages/habitat/features/habitat/habitat/habitat-api/tls-ca-auth.test.ts",
    "packages/habitat/features/habitat/habitat/routes/index.ts",
    "packages/habitat/features/habitat/habitat/tts-handler.test.ts",
    "packages/habitat/features/habitat/habitat/tts-handler.ts",
    "packages/habitat/features/health/cordis-plugin.ts",
    "packages/habitat/features/mcp/cordis-plugin.ts",
    "packages/habitat/features/note/cordis-plugin.ts",
    "packages/habitat/features/notification/cordis-plugin.ts",
    "packages/habitat/features/notification/habitat/runtime-deps.ts",
    "packages/habitat/features/object-storage/cordis-plugin.ts",
    "packages/habitat/features/object-storage/domain/bun-s3.ts",
    "packages/habitat/features/object-storage/domain/object-store.ts",
    "packages/habitat/features/objective/cordis-plugin.ts",
    "packages/habitat/features/pomodoro/cordis-plugin.ts",
    "packages/habitat/features/project/cordis-plugin.ts",
    "packages/habitat/features/room/cordis-plugin.ts",
    "packages/habitat/features/shell-quick/cordis-plugin.ts",
    "packages/habitat/features/subagent/cordis-plugin.ts",
    "packages/habitat/features/subagent/domain/subagent-tools.ts",
    "packages/habitat/features/tag/cordis-plugin.ts",
    "packages/habitat/features/task/cordis-plugin.ts",
    "packages/habitat/features/task/domain/item-store.ts",
    "packages/habitat/features/task/habitat/advance-reminder-stream.ts",
    "packages/habitat/features/vault/cordis-plugin.ts",
    "packages/habitat/features/workflow/domain/runner.ts",
    "packages/habitat/features/workflow/domain/workflow-tools.ts",
  ],
  "kernel -> core": [
    "packages/habitat/kernel/loop-mechanism/conversation-loop-side-effects.ts",
    "packages/habitat/kernel/loop-mechanism/engine-run.test.ts",
    "packages/habitat/kernel/loop-mechanism/index.ts",
    "packages/habitat/kernel/loop-mechanism/llm-debug-snapshot.test.ts",
    "packages/habitat/kernel/loop-mechanism/llm-debug-snapshot.ts",
    "packages/habitat/kernel/loop-mechanism/loop-engine.ts",
    "packages/habitat/kernel/loop-mechanism/loop-injection.test.ts",
    "packages/habitat/kernel/loop-mechanism/resolve-engine-tool-schemas.test.ts",
    "packages/habitat/kernel/loop-mechanism/stream-reply/tool-round-buffer.ts",
    "packages/habitat/kernel/loop-mechanism/stream-reply/types.ts",
    "packages/habitat/kernel/loop-mechanism/tool-progress-continue.test.ts",
  ],
  "portal -> core": ["packages/frontend/portal/vite-config-cross-pkg.ts"],
  "portal-sdk -> core": ["packages/frontend/client/portal-sdk/speech/edge-voices.ts"],
  "portal-sdk -> portal": ["packages/frontend/client/portal-sdk/pomodoro-active.ts"],
  "ui-features -> app-frame": [
    "packages/frontend/features/coding/build.ts",
    "packages/frontend/features/coding/vite.config.ts",
    "packages/frontend/features/companion/build.ts",
    "packages/frontend/features/companion/vite.config.ts",
    "packages/frontend/features/pomodoro/build-float.ts",
    "packages/frontend/features/pomodoro/vite.float.config.ts",
  ],
  "ui-features -> features": [
    "packages/frontend/features/habitat/ui/habitat/lib/api.ts",
    "packages/frontend/features/habitat/ui/habitat/lib/format-datetime.ts",
    "packages/frontend/features/habitat/ui/habitat/routes/_sidebar/self-layer.tsx",
    "packages/frontend/features/habitat/ui/habitat/routes/_sidebar/system-prompt.tsx",
    "packages/frontend/features/habitat/ui/habitat/routes/_sidebar/tools.tsx",
  ],
  "ui-features -> portal": [
    "packages/frontend/features/coding/ui/spa/main.tsx",
    "packages/frontend/features/companion/ui/spa/main.tsx",
    "packages/frontend/features/pomodoro/ui/float/main.tsx",
  ],
  "ui-kit -> portal-sdk": [
    "packages/frontend/ui-kit/composite/EntityIdLabel.tsx",
    "packages/frontend/ui-kit/lib/task-list-tree.ts",
  ],
};
