/**
 * 由 `bun scripts/check-module-globals.ts --update` 生成 —— 勿手改。
 * 模块级全局桥存量文件清单；只减不增，P3 完成后为空。
 */
export const MODULE_GLOBALS_BASELINE: Readonly<Record<string, readonly string[]>> = {
  "Symbol.for-appRuntime": ["packages/habitat/platform/ports/app-runtime-context.ts"],
  "Symbol.for-process-context": [
    "packages/habitat/platform/service/process-context.ts",
    "packages/habitat/platform/service/runtime-context.ts",
  ],
  ensureProcessContext: [
    "packages/habitat/capabilities/connectors/cron/module.ts",
    "packages/habitat/capabilities/connectors/vault/user-secrets.ts",
    "packages/habitat/capabilities/federation/hub-runtime-context.ts",
    "packages/habitat/capabilities/federation/runtime-context.ts",
    "packages/habitat/capabilities/federation/satellite-rpc.ts",
    "packages/habitat/capabilities/memory/service/reflect.ts",
    "packages/habitat/capabilities/memory/service/retain-engine-port.ts",
    "packages/habitat/capabilities/outpost/transport/runtime-context.ts",
    "packages/habitat/capabilities/tools/browser-camofox.ts",
    "packages/habitat/capabilities/tools/clarify/clarify.ts",
    "packages/habitat/capabilities/tools/docs-corpus.ts",
    "packages/habitat/capabilities/tools/web.ts",
    "packages/habitat/core/compress/compression-summary-scheduler.ts",
    "packages/habitat/core/config/capability-injection.ts",
    "packages/habitat/core/db/pg/client.ts",
    "packages/habitat/core/db/pg/embedding/runtime.ts",
    "packages/habitat/core/db/pg/search/runtime.ts",
    "packages/habitat/core/llm/llm-stack.test.ts",
    "packages/habitat/core/redis/client.ts",
    "packages/habitat/core/skill/project-overlay.ts",
    "packages/habitat/core/soft-failure/notify.ts",
    "packages/habitat/core/tokenizer/resolve-context.ts",
    "packages/habitat/core/tool/conversation-tools.test.ts",
    "packages/habitat/core/tool/default-conversation-toolsets.test.ts",
    "packages/habitat/features/email/domain/sync-port.ts",
    "packages/habitat/features/object-storage/domain/object-store.ts",
    "packages/habitat/platform/bootstrap/kernel.ts",
    "packages/habitat/platform/config/register-runtime-applies.ts",
    "packages/habitat/platform/features/registry.ts",
    "packages/habitat/platform/serve.ts",
    "packages/habitat/platform/service/auto-llm-run.test.ts",
    "packages/habitat/platform/service/conversation-title.test.ts",
    "packages/habitat/platform/service/env-health/baseline.ts",
    "packages/habitat/platform/service/process-context.ts",
    "packages/habitat/platform/service/service-messaging.client-op.test.ts",
    "packages/habitat/platform/service/service-messaging.commands.test.ts",
    "packages/habitat/platform/service/stream-done-order.test.ts",
    "packages/habitat/platform/service/turn-lifecycle.test.ts",
  ],
  getProcessContext: [
    "packages/habitat/capabilities/connectors/cron/module.ts",
    "packages/habitat/capabilities/connectors/vault/user-secrets.ts",
    "packages/habitat/capabilities/federation/hub-runtime-context.ts",
    "packages/habitat/capabilities/federation/runtime-context.ts",
    "packages/habitat/capabilities/federation/satellite-rpc.ts",
    "packages/habitat/capabilities/memory/service/reflect.ts",
    "packages/habitat/capabilities/memory/service/retain-engine-port.ts",
    "packages/habitat/capabilities/outpost/transport/runtime-context.ts",
    "packages/habitat/capabilities/tools/browser-camofox.ts",
    "packages/habitat/capabilities/tools/clarify/clarify.ts",
    "packages/habitat/capabilities/tools/docs-corpus.ts",
    "packages/habitat/capabilities/tools/notification/port.ts",
    "packages/habitat/capabilities/tools/web.ts",
    "packages/habitat/core/compress/compression-summary-scheduler.ts",
    "packages/habitat/core/config/capability-injection.ts",
    "packages/habitat/core/db/pg/client.ts",
    "packages/habitat/core/db/pg/embedding/runtime.ts",
    "packages/habitat/core/db/pg/search/runtime.ts",
    "packages/habitat/core/hooks/prompt/runner.test.ts",
    "packages/habitat/core/hooks/prompt/runner.ts",
    "packages/habitat/core/llm/llm-stack-configurator.ts",
    "packages/habitat/core/llm/llm-stack-runtime.ts",
    "packages/habitat/core/redis/client.ts",
    "packages/habitat/core/skill/project-overlay.ts",
    "packages/habitat/core/soft-failure/notify.ts",
    "packages/habitat/core/tokenizer/resolve-context.ts",
    "packages/habitat/core/tool/policy-port.ts",
    "packages/habitat/features/email/domain/sync-port.ts",
    "packages/habitat/features/object-storage/domain/object-store.ts",
    "packages/habitat/platform/config/register-runtime-applies.ts",
    "packages/habitat/platform/features/service.ts",
    "packages/habitat/platform/service/process-context.ts",
  ],
  "globalThis-GlobalStore": [
    "packages/habitat/platform/service/process-context.ts",
    "packages/habitat/platform/service/runtime-context.ts",
  ],
  resetProcessContextForTests: ["packages/habitat/platform/service/process-context.ts"],
};
