/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WorkshopRouteImport } from "./routes/workshop";
import { Route as StudioRouteRouteImport } from "./routes/studio/route";
import { Route as ParlorRouteRouteImport } from "./routes/parlor/route";
import { Route as ChamberRouteRouteImport } from "./routes/chamber/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as WorkshopPathRouteImport } from "./routes/workshop/$path";
import { Route as StudioShortVideoRouteImport } from "./routes/studio/short-video";
import { Route as StudioPairProgrammingRouteImport } from "./routes/studio/pair-programming";
import { Route as StudioNovelRouteImport } from "./routes/studio/novel";
import { Route as ParlorSessionsRouteImport } from "./routes/parlor/sessions";
import { Route as ParlorChatRouteImport } from "./routes/parlor/chat";
import { Route as ChamberToolsRouteImport } from "./routes/chamber/tools";
import { Route as ChamberTasksRouteImport } from "./routes/chamber/tasks";
import { Route as ChamberSystemPromptRouteImport } from "./routes/chamber/system-prompt";
import { Route as ChamberSleepRouteImport } from "./routes/chamber/sleep";
import { Route as ChamberSemanticMemoryRouteImport } from "./routes/chamber/semantic-memory";
import { Route as ChamberSelfLayerRouteImport } from "./routes/chamber/self-layer";
import { Route as ChamberMemoryRouteImport } from "./routes/chamber/memory";
import { Route as ChamberMcpRouteImport } from "./routes/chamber/mcp";
import { Route as ChamberSatellitesRouteImport } from "./routes/chamber/satellites";
import { Route as ChamberLimbicMemoryRouteImport } from "./routes/chamber/limbic-memory";
import { Route as ChamberFtsRouteImport } from "./routes/chamber/fts";
import { Route as ChamberFridgeMagnetRouteImport } from "./routes/chamber/fridge-magnet";
import { Route as ChamberEmailRouteImport } from "./routes/chamber/email";
import { Route as ChamberDreamRouteImport } from "./routes/chamber/dream";
import { Route as ChamberDashboardRouteImport } from "./routes/chamber/dashboard";
import { Route as ChamberCronRouteImport } from "./routes/chamber/cron";
import { Route as ChamberCredentialsRouteImport } from "./routes/chamber/credentials";
import { Route as ChamberConfigRouteImport } from "./routes/chamber/config";
import { Route as ChamberCommandsRouteImport } from "./routes/chamber/commands";
import { Route as ChamberAutobiographicalMemoryRouteImport } from "./routes/chamber/autobiographical-memory";
import { Route as ChamberAcpRouteImport } from "./routes/chamber/acp";
import { Route as ChamberSessionsRouteRouteImport } from "./routes/chamber/sessions/route";
import { Route as ChamberSessionsIndexRouteImport } from "./routes/chamber/sessions/index";
import { Route as ChamberSessionsSessionIdRouteImport } from "./routes/chamber/sessions/$sessionId";

const WorkshopRoute = WorkshopRouteImport.update({
  id: "/workshop",
  path: "/workshop",
  getParentRoute: () => rootRouteImport,
} as any);
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: "/studio",
  path: "/studio",
  getParentRoute: () => rootRouteImport,
} as any);
const ParlorRouteRoute = ParlorRouteRouteImport.update({
  id: "/parlor",
  path: "/parlor",
  getParentRoute: () => rootRouteImport,
} as any);
const ChamberRouteRoute = ChamberRouteRouteImport.update({
  id: "/chamber",
  path: "/chamber",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkshopPathRoute = WorkshopPathRouteImport.update({
  id: "/$path",
  path: "/$path",
  getParentRoute: () => WorkshopRoute,
} as any);
const StudioShortVideoRoute = StudioShortVideoRouteImport.update({
  id: "/short-video",
  path: "/short-video",
  getParentRoute: () => StudioRouteRoute,
} as any);
const StudioPairProgrammingRoute = StudioPairProgrammingRouteImport.update({
  id: "/pair-programming",
  path: "/pair-programming",
  getParentRoute: () => StudioRouteRoute,
} as any);
const StudioNovelRoute = StudioNovelRouteImport.update({
  id: "/novel",
  path: "/novel",
  getParentRoute: () => StudioRouteRoute,
} as any);
const ParlorSessionsRoute = ParlorSessionsRouteImport.update({
  id: "/sessions",
  path: "/sessions",
  getParentRoute: () => ParlorRouteRoute,
} as any);
const ParlorChatRoute = ParlorChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => ParlorRouteRoute,
} as any);
const ChamberToolsRoute = ChamberToolsRouteImport.update({
  id: "/tools",
  path: "/tools",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberTasksRoute = ChamberTasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberSystemPromptRoute = ChamberSystemPromptRouteImport.update({
  id: "/system-prompt",
  path: "/system-prompt",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberSleepRoute = ChamberSleepRouteImport.update({
  id: "/sleep",
  path: "/sleep",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberSemanticMemoryRoute = ChamberSemanticMemoryRouteImport.update({
  id: "/semantic-memory",
  path: "/semantic-memory",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberSelfLayerRoute = ChamberSelfLayerRouteImport.update({
  id: "/self-layer",
  path: "/self-layer",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberMemoryRoute = ChamberMemoryRouteImport.update({
  id: "/memory",
  path: "/memory",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberMcpRoute = ChamberMcpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberSatellitesRoute = ChamberSatellitesRouteImport.update({
  id: "/satellites",
  path: "/satellites",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberLimbicMemoryRoute = ChamberLimbicMemoryRouteImport.update({
  id: "/limbic-memory",
  path: "/limbic-memory",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberFtsRoute = ChamberFtsRouteImport.update({
  id: "/fts",
  path: "/fts",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberFridgeMagnetRoute = ChamberFridgeMagnetRouteImport.update({
  id: "/fridge-magnet",
  path: "/fridge-magnet",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberEmailRoute = ChamberEmailRouteImport.update({
  id: "/email",
  path: "/email",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberDreamRoute = ChamberDreamRouteImport.update({
  id: "/dream",
  path: "/dream",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberDashboardRoute = ChamberDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberCronRoute = ChamberCronRouteImport.update({
  id: "/cron",
  path: "/cron",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberCredentialsRoute = ChamberCredentialsRouteImport.update({
  id: "/credentials",
  path: "/credentials",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberConfigRoute = ChamberConfigRouteImport.update({
  id: "/config",
  path: "/config",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberCommandsRoute = ChamberCommandsRouteImport.update({
  id: "/commands",
  path: "/commands",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberAutobiographicalMemoryRoute = ChamberAutobiographicalMemoryRouteImport.update({
  id: "/autobiographical-memory",
  path: "/autobiographical-memory",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberAcpRoute = ChamberAcpRouteImport.update({
  id: "/acp",
  path: "/acp",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberSessionsRouteRoute = ChamberSessionsRouteRouteImport.update({
  id: "/sessions",
  path: "/sessions",
  getParentRoute: () => ChamberRouteRoute,
} as any);
const ChamberSessionsIndexRoute = ChamberSessionsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ChamberSessionsRouteRoute,
} as any);
const ChamberSessionsSessionIdRoute = ChamberSessionsSessionIdRouteImport.update({
  id: "/$sessionId",
  path: "/$sessionId",
  getParentRoute: () => ChamberSessionsRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/chamber": typeof ChamberRouteRouteWithChildren;
  "/parlor": typeof ParlorRouteRouteWithChildren;
  "/studio": typeof StudioRouteRouteWithChildren;
  "/workshop": typeof WorkshopRouteWithChildren;
  "/chamber/sessions": typeof ChamberSessionsRouteRouteWithChildren;
  "/chamber/acp": typeof ChamberAcpRoute;
  "/chamber/autobiographical-memory": typeof ChamberAutobiographicalMemoryRoute;
  "/chamber/commands": typeof ChamberCommandsRoute;
  "/chamber/config": typeof ChamberConfigRoute;
  "/chamber/credentials": typeof ChamberCredentialsRoute;
  "/chamber/cron": typeof ChamberCronRoute;
  "/chamber/dashboard": typeof ChamberDashboardRoute;
  "/chamber/dream": typeof ChamberDreamRoute;
  "/chamber/email": typeof ChamberEmailRoute;
  "/chamber/fridge-magnet": typeof ChamberFridgeMagnetRoute;
  "/chamber/fts": typeof ChamberFtsRoute;
  "/chamber/limbic-memory": typeof ChamberLimbicMemoryRoute;
  "/chamber/mcp": typeof ChamberMcpRoute;
  "/chamber/satellites": typeof ChamberSatellitesRoute;
  "/chamber/memory": typeof ChamberMemoryRoute;
  "/chamber/self-layer": typeof ChamberSelfLayerRoute;
  "/chamber/semantic-memory": typeof ChamberSemanticMemoryRoute;
  "/chamber/sleep": typeof ChamberSleepRoute;
  "/chamber/system-prompt": typeof ChamberSystemPromptRoute;
  "/chamber/tasks": typeof ChamberTasksRoute;
  "/chamber/tools": typeof ChamberToolsRoute;
  "/parlor/chat": typeof ParlorChatRoute;
  "/parlor/sessions": typeof ParlorSessionsRoute;
  "/studio/novel": typeof StudioNovelRoute;
  "/studio/pair-programming": typeof StudioPairProgrammingRoute;
  "/studio/short-video": typeof StudioShortVideoRoute;
  "/workshop/$path": typeof WorkshopPathRoute;
  "/chamber/sessions/$sessionId": typeof ChamberSessionsSessionIdRoute;
  "/chamber/sessions/": typeof ChamberSessionsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/chamber": typeof ChamberRouteRouteWithChildren;
  "/parlor": typeof ParlorRouteRouteWithChildren;
  "/studio": typeof StudioRouteRouteWithChildren;
  "/workshop": typeof WorkshopRouteWithChildren;
  "/chamber/acp": typeof ChamberAcpRoute;
  "/chamber/autobiographical-memory": typeof ChamberAutobiographicalMemoryRoute;
  "/chamber/commands": typeof ChamberCommandsRoute;
  "/chamber/config": typeof ChamberConfigRoute;
  "/chamber/credentials": typeof ChamberCredentialsRoute;
  "/chamber/cron": typeof ChamberCronRoute;
  "/chamber/dashboard": typeof ChamberDashboardRoute;
  "/chamber/dream": typeof ChamberDreamRoute;
  "/chamber/email": typeof ChamberEmailRoute;
  "/chamber/fridge-magnet": typeof ChamberFridgeMagnetRoute;
  "/chamber/fts": typeof ChamberFtsRoute;
  "/chamber/limbic-memory": typeof ChamberLimbicMemoryRoute;
  "/chamber/mcp": typeof ChamberMcpRoute;
  "/chamber/satellites": typeof ChamberSatellitesRoute;
  "/chamber/memory": typeof ChamberMemoryRoute;
  "/chamber/self-layer": typeof ChamberSelfLayerRoute;
  "/chamber/semantic-memory": typeof ChamberSemanticMemoryRoute;
  "/chamber/sleep": typeof ChamberSleepRoute;
  "/chamber/system-prompt": typeof ChamberSystemPromptRoute;
  "/chamber/tasks": typeof ChamberTasksRoute;
  "/chamber/tools": typeof ChamberToolsRoute;
  "/parlor/chat": typeof ParlorChatRoute;
  "/parlor/sessions": typeof ParlorSessionsRoute;
  "/studio/novel": typeof StudioNovelRoute;
  "/studio/pair-programming": typeof StudioPairProgrammingRoute;
  "/studio/short-video": typeof StudioShortVideoRoute;
  "/workshop/$path": typeof WorkshopPathRoute;
  "/chamber/sessions/$sessionId": typeof ChamberSessionsSessionIdRoute;
  "/chamber/sessions": typeof ChamberSessionsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/chamber": typeof ChamberRouteRouteWithChildren;
  "/parlor": typeof ParlorRouteRouteWithChildren;
  "/studio": typeof StudioRouteRouteWithChildren;
  "/workshop": typeof WorkshopRouteWithChildren;
  "/chamber/sessions": typeof ChamberSessionsRouteRouteWithChildren;
  "/chamber/acp": typeof ChamberAcpRoute;
  "/chamber/autobiographical-memory": typeof ChamberAutobiographicalMemoryRoute;
  "/chamber/commands": typeof ChamberCommandsRoute;
  "/chamber/config": typeof ChamberConfigRoute;
  "/chamber/credentials": typeof ChamberCredentialsRoute;
  "/chamber/cron": typeof ChamberCronRoute;
  "/chamber/dashboard": typeof ChamberDashboardRoute;
  "/chamber/dream": typeof ChamberDreamRoute;
  "/chamber/email": typeof ChamberEmailRoute;
  "/chamber/fridge-magnet": typeof ChamberFridgeMagnetRoute;
  "/chamber/fts": typeof ChamberFtsRoute;
  "/chamber/limbic-memory": typeof ChamberLimbicMemoryRoute;
  "/chamber/mcp": typeof ChamberMcpRoute;
  "/chamber/satellites": typeof ChamberSatellitesRoute;
  "/chamber/memory": typeof ChamberMemoryRoute;
  "/chamber/self-layer": typeof ChamberSelfLayerRoute;
  "/chamber/semantic-memory": typeof ChamberSemanticMemoryRoute;
  "/chamber/sleep": typeof ChamberSleepRoute;
  "/chamber/system-prompt": typeof ChamberSystemPromptRoute;
  "/chamber/tasks": typeof ChamberTasksRoute;
  "/chamber/tools": typeof ChamberToolsRoute;
  "/parlor/chat": typeof ParlorChatRoute;
  "/parlor/sessions": typeof ParlorSessionsRoute;
  "/studio/novel": typeof StudioNovelRoute;
  "/studio/pair-programming": typeof StudioPairProgrammingRoute;
  "/studio/short-video": typeof StudioShortVideoRoute;
  "/workshop/$path": typeof WorkshopPathRoute;
  "/chamber/sessions/$sessionId": typeof ChamberSessionsSessionIdRoute;
  "/chamber/sessions/": typeof ChamberSessionsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/chamber"
    | "/parlor"
    | "/studio"
    | "/workshop"
    | "/chamber/sessions"
    | "/chamber/acp"
    | "/chamber/autobiographical-memory"
    | "/chamber/commands"
    | "/chamber/config"
    | "/chamber/credentials"
    | "/chamber/cron"
    | "/chamber/dashboard"
    | "/chamber/dream"
    | "/chamber/email"
    | "/chamber/fridge-magnet"
    | "/chamber/fts"
    | "/chamber/limbic-memory"
    | "/chamber/mcp"
    | "/chamber/satellites"
    | "/chamber/memory"
    | "/chamber/self-layer"
    | "/chamber/semantic-memory"
    | "/chamber/sleep"
    | "/chamber/system-prompt"
    | "/chamber/tasks"
    | "/chamber/tools"
    | "/parlor/chat"
    | "/parlor/sessions"
    | "/studio/novel"
    | "/studio/pair-programming"
    | "/studio/short-video"
    | "/workshop/$path"
    | "/chamber/sessions/$sessionId"
    | "/chamber/sessions/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/chamber"
    | "/parlor"
    | "/studio"
    | "/workshop"
    | "/chamber/acp"
    | "/chamber/autobiographical-memory"
    | "/chamber/commands"
    | "/chamber/config"
    | "/chamber/credentials"
    | "/chamber/cron"
    | "/chamber/dashboard"
    | "/chamber/dream"
    | "/chamber/email"
    | "/chamber/fridge-magnet"
    | "/chamber/fts"
    | "/chamber/limbic-memory"
    | "/chamber/mcp"
    | "/chamber/satellites"
    | "/chamber/memory"
    | "/chamber/self-layer"
    | "/chamber/semantic-memory"
    | "/chamber/sleep"
    | "/chamber/system-prompt"
    | "/chamber/tasks"
    | "/chamber/tools"
    | "/parlor/chat"
    | "/parlor/sessions"
    | "/studio/novel"
    | "/studio/pair-programming"
    | "/studio/short-video"
    | "/workshop/$path"
    | "/chamber/sessions/$sessionId"
    | "/chamber/sessions";
  id:
    | "__root__"
    | "/"
    | "/chamber"
    | "/parlor"
    | "/studio"
    | "/workshop"
    | "/chamber/sessions"
    | "/chamber/acp"
    | "/chamber/autobiographical-memory"
    | "/chamber/commands"
    | "/chamber/config"
    | "/chamber/credentials"
    | "/chamber/cron"
    | "/chamber/dashboard"
    | "/chamber/dream"
    | "/chamber/email"
    | "/chamber/fridge-magnet"
    | "/chamber/fts"
    | "/chamber/limbic-memory"
    | "/chamber/mcp"
    | "/chamber/satellites"
    | "/chamber/memory"
    | "/chamber/self-layer"
    | "/chamber/semantic-memory"
    | "/chamber/sleep"
    | "/chamber/system-prompt"
    | "/chamber/tasks"
    | "/chamber/tools"
    | "/parlor/chat"
    | "/parlor/sessions"
    | "/studio/novel"
    | "/studio/pair-programming"
    | "/studio/short-video"
    | "/workshop/$path"
    | "/chamber/sessions/$sessionId"
    | "/chamber/sessions/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ChamberRouteRoute: typeof ChamberRouteRouteWithChildren;
  ParlorRouteRoute: typeof ParlorRouteRouteWithChildren;
  StudioRouteRoute: typeof StudioRouteRouteWithChildren;
  WorkshopRoute: typeof WorkshopRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workshop": {
      id: "/workshop";
      path: "/workshop";
      fullPath: "/workshop";
      preLoaderRoute: typeof WorkshopRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/studio": {
      id: "/studio";
      path: "/studio";
      fullPath: "/studio";
      preLoaderRoute: typeof StudioRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/parlor": {
      id: "/parlor";
      path: "/parlor";
      fullPath: "/parlor";
      preLoaderRoute: typeof ParlorRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chamber": {
      id: "/chamber";
      path: "/chamber";
      fullPath: "/chamber";
      preLoaderRoute: typeof ChamberRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workshop/$path": {
      id: "/workshop/$path";
      path: "/$path";
      fullPath: "/workshop/$path";
      preLoaderRoute: typeof WorkshopPathRouteImport;
      parentRoute: typeof WorkshopRoute;
    };
    "/studio/short-video": {
      id: "/studio/short-video";
      path: "/short-video";
      fullPath: "/studio/short-video";
      preLoaderRoute: typeof StudioShortVideoRouteImport;
      parentRoute: typeof StudioRouteRoute;
    };
    "/studio/pair-programming": {
      id: "/studio/pair-programming";
      path: "/pair-programming";
      fullPath: "/studio/pair-programming";
      preLoaderRoute: typeof StudioPairProgrammingRouteImport;
      parentRoute: typeof StudioRouteRoute;
    };
    "/studio/novel": {
      id: "/studio/novel";
      path: "/novel";
      fullPath: "/studio/novel";
      preLoaderRoute: typeof StudioNovelRouteImport;
      parentRoute: typeof StudioRouteRoute;
    };
    "/parlor/sessions": {
      id: "/parlor/sessions";
      path: "/sessions";
      fullPath: "/parlor/sessions";
      preLoaderRoute: typeof ParlorSessionsRouteImport;
      parentRoute: typeof ParlorRouteRoute;
    };
    "/parlor/chat": {
      id: "/parlor/chat";
      path: "/chat";
      fullPath: "/parlor/chat";
      preLoaderRoute: typeof ParlorChatRouteImport;
      parentRoute: typeof ParlorRouteRoute;
    };
    "/chamber/tools": {
      id: "/chamber/tools";
      path: "/tools";
      fullPath: "/chamber/tools";
      preLoaderRoute: typeof ChamberToolsRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/tasks": {
      id: "/chamber/tasks";
      path: "/tasks";
      fullPath: "/chamber/tasks";
      preLoaderRoute: typeof ChamberTasksRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/system-prompt": {
      id: "/chamber/system-prompt";
      path: "/system-prompt";
      fullPath: "/chamber/system-prompt";
      preLoaderRoute: typeof ChamberSystemPromptRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/sleep": {
      id: "/chamber/sleep";
      path: "/sleep";
      fullPath: "/chamber/sleep";
      preLoaderRoute: typeof ChamberSleepRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/semantic-memory": {
      id: "/chamber/semantic-memory";
      path: "/semantic-memory";
      fullPath: "/chamber/semantic-memory";
      preLoaderRoute: typeof ChamberSemanticMemoryRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/self-layer": {
      id: "/chamber/self-layer";
      path: "/self-layer";
      fullPath: "/chamber/self-layer";
      preLoaderRoute: typeof ChamberSelfLayerRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/memory": {
      id: "/chamber/memory";
      path: "/memory";
      fullPath: "/chamber/memory";
      preLoaderRoute: typeof ChamberMemoryRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/mcp": {
      id: "/chamber/mcp";
      path: "/mcp";
      fullPath: "/chamber/mcp";
      preLoaderRoute: typeof ChamberMcpRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/satellites": {
      id: "/chamber/satellites";
      path: "/satellites";
      fullPath: "/chamber/satellites";
      preLoaderRoute: typeof ChamberSatellitesRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/limbic-memory": {
      id: "/chamber/limbic-memory";
      path: "/limbic-memory";
      fullPath: "/chamber/limbic-memory";
      preLoaderRoute: typeof ChamberLimbicMemoryRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/fts": {
      id: "/chamber/fts";
      path: "/fts";
      fullPath: "/chamber/fts";
      preLoaderRoute: typeof ChamberFtsRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/fridge-magnet": {
      id: "/chamber/fridge-magnet";
      path: "/fridge-magnet";
      fullPath: "/chamber/fridge-magnet";
      preLoaderRoute: typeof ChamberFridgeMagnetRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/email": {
      id: "/chamber/email";
      path: "/email";
      fullPath: "/chamber/email";
      preLoaderRoute: typeof ChamberEmailRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/dream": {
      id: "/chamber/dream";
      path: "/dream";
      fullPath: "/chamber/dream";
      preLoaderRoute: typeof ChamberDreamRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/dashboard": {
      id: "/chamber/dashboard";
      path: "/dashboard";
      fullPath: "/chamber/dashboard";
      preLoaderRoute: typeof ChamberDashboardRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/cron": {
      id: "/chamber/cron";
      path: "/cron";
      fullPath: "/chamber/cron";
      preLoaderRoute: typeof ChamberCronRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/credentials": {
      id: "/chamber/credentials";
      path: "/credentials";
      fullPath: "/chamber/credentials";
      preLoaderRoute: typeof ChamberCredentialsRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/config": {
      id: "/chamber/config";
      path: "/config";
      fullPath: "/chamber/config";
      preLoaderRoute: typeof ChamberConfigRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/commands": {
      id: "/chamber/commands";
      path: "/commands";
      fullPath: "/chamber/commands";
      preLoaderRoute: typeof ChamberCommandsRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/autobiographical-memory": {
      id: "/chamber/autobiographical-memory";
      path: "/autobiographical-memory";
      fullPath: "/chamber/autobiographical-memory";
      preLoaderRoute: typeof ChamberAutobiographicalMemoryRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/acp": {
      id: "/chamber/acp";
      path: "/acp";
      fullPath: "/chamber/acp";
      preLoaderRoute: typeof ChamberAcpRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/sessions": {
      id: "/chamber/sessions";
      path: "/sessions";
      fullPath: "/chamber/sessions";
      preLoaderRoute: typeof ChamberSessionsRouteRouteImport;
      parentRoute: typeof ChamberRouteRoute;
    };
    "/chamber/sessions/": {
      id: "/chamber/sessions/";
      path: "/";
      fullPath: "/chamber/sessions/";
      preLoaderRoute: typeof ChamberSessionsIndexRouteImport;
      parentRoute: typeof ChamberSessionsRouteRoute;
    };
    "/chamber/sessions/$sessionId": {
      id: "/chamber/sessions/$sessionId";
      path: "/$sessionId";
      fullPath: "/chamber/sessions/$sessionId";
      preLoaderRoute: typeof ChamberSessionsSessionIdRouteImport;
      parentRoute: typeof ChamberSessionsRouteRoute;
    };
  }
}

interface ChamberSessionsRouteRouteChildren {
  ChamberSessionsSessionIdRoute: typeof ChamberSessionsSessionIdRoute;
  ChamberSessionsIndexRoute: typeof ChamberSessionsIndexRoute;
}

const ChamberSessionsRouteRouteChildren: ChamberSessionsRouteRouteChildren = {
  ChamberSessionsSessionIdRoute: ChamberSessionsSessionIdRoute,
  ChamberSessionsIndexRoute: ChamberSessionsIndexRoute,
};

const ChamberSessionsRouteRouteWithChildren = ChamberSessionsRouteRoute._addFileChildren(
  ChamberSessionsRouteRouteChildren,
);

interface ChamberRouteRouteChildren {
  ChamberSessionsRouteRoute: typeof ChamberSessionsRouteRouteWithChildren;
  ChamberAcpRoute: typeof ChamberAcpRoute;
  ChamberAutobiographicalMemoryRoute: typeof ChamberAutobiographicalMemoryRoute;
  ChamberCommandsRoute: typeof ChamberCommandsRoute;
  ChamberConfigRoute: typeof ChamberConfigRoute;
  ChamberCredentialsRoute: typeof ChamberCredentialsRoute;
  ChamberCronRoute: typeof ChamberCronRoute;
  ChamberDashboardRoute: typeof ChamberDashboardRoute;
  ChamberDreamRoute: typeof ChamberDreamRoute;
  ChamberEmailRoute: typeof ChamberEmailRoute;
  ChamberFridgeMagnetRoute: typeof ChamberFridgeMagnetRoute;
  ChamberFtsRoute: typeof ChamberFtsRoute;
  ChamberLimbicMemoryRoute: typeof ChamberLimbicMemoryRoute;
  ChamberMcpRoute: typeof ChamberMcpRoute;
  ChamberSatellitesRoute: typeof ChamberSatellitesRoute;
  ChamberMemoryRoute: typeof ChamberMemoryRoute;
  ChamberSelfLayerRoute: typeof ChamberSelfLayerRoute;
  ChamberSemanticMemoryRoute: typeof ChamberSemanticMemoryRoute;
  ChamberSleepRoute: typeof ChamberSleepRoute;
  ChamberSystemPromptRoute: typeof ChamberSystemPromptRoute;
  ChamberTasksRoute: typeof ChamberTasksRoute;
  ChamberToolsRoute: typeof ChamberToolsRoute;
}

const ChamberRouteRouteChildren: ChamberRouteRouteChildren = {
  ChamberSessionsRouteRoute: ChamberSessionsRouteRouteWithChildren,
  ChamberAcpRoute: ChamberAcpRoute,
  ChamberAutobiographicalMemoryRoute: ChamberAutobiographicalMemoryRoute,
  ChamberCommandsRoute: ChamberCommandsRoute,
  ChamberConfigRoute: ChamberConfigRoute,
  ChamberCredentialsRoute: ChamberCredentialsRoute,
  ChamberCronRoute: ChamberCronRoute,
  ChamberDashboardRoute: ChamberDashboardRoute,
  ChamberDreamRoute: ChamberDreamRoute,
  ChamberEmailRoute: ChamberEmailRoute,
  ChamberFridgeMagnetRoute: ChamberFridgeMagnetRoute,
  ChamberFtsRoute: ChamberFtsRoute,
  ChamberLimbicMemoryRoute: ChamberLimbicMemoryRoute,
  ChamberMcpRoute: ChamberMcpRoute,
  ChamberSatellitesRoute: ChamberSatellitesRoute,
  ChamberMemoryRoute: ChamberMemoryRoute,
  ChamberSelfLayerRoute: ChamberSelfLayerRoute,
  ChamberSemanticMemoryRoute: ChamberSemanticMemoryRoute,
  ChamberSleepRoute: ChamberSleepRoute,
  ChamberSystemPromptRoute: ChamberSystemPromptRoute,
  ChamberTasksRoute: ChamberTasksRoute,
  ChamberToolsRoute: ChamberToolsRoute,
};

const ChamberRouteRouteWithChildren = ChamberRouteRoute._addFileChildren(ChamberRouteRouteChildren);

interface ParlorRouteRouteChildren {
  ParlorChatRoute: typeof ParlorChatRoute;
  ParlorSessionsRoute: typeof ParlorSessionsRoute;
}

const ParlorRouteRouteChildren: ParlorRouteRouteChildren = {
  ParlorChatRoute: ParlorChatRoute,
  ParlorSessionsRoute: ParlorSessionsRoute,
};

const ParlorRouteRouteWithChildren = ParlorRouteRoute._addFileChildren(ParlorRouteRouteChildren);

interface StudioRouteRouteChildren {
  StudioNovelRoute: typeof StudioNovelRoute;
  StudioPairProgrammingRoute: typeof StudioPairProgrammingRoute;
  StudioShortVideoRoute: typeof StudioShortVideoRoute;
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioNovelRoute: StudioNovelRoute,
  StudioPairProgrammingRoute: StudioPairProgrammingRoute,
  StudioShortVideoRoute: StudioShortVideoRoute,
};

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(StudioRouteRouteChildren);

interface WorkshopRouteChildren {
  WorkshopPathRoute: typeof WorkshopPathRoute;
}

const WorkshopRouteChildren: WorkshopRouteChildren = {
  WorkshopPathRoute: WorkshopPathRoute,
};

const WorkshopRouteWithChildren = WorkshopRoute._addFileChildren(WorkshopRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChamberRouteRoute: ChamberRouteRouteWithChildren,
  ParlorRouteRoute: ParlorRouteRouteWithChildren,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  WorkshopRoute: WorkshopRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
