import {
  tasklistCreateInputSchema,
  tasklistCreateOutputSchema,
  tasklistDeleteInputSchema,
  tasklistDeleteOutputSchema,
  tasklistListInputSchema,
  tasklistListOutputSchema,
  tasklistPatchInputSchema,
  tasklistPatchOutputSchema,
  tasklistItemListInputSchema,
  tasklistItemListOutputSchema,
  tasklistItemCreateInputSchema,
  tasklistItemCreateOutputSchema,
  projectItemListInputSchema,
  projectItemListOutputSchema,
  projectItemCreateInputSchema,
  projectItemCreateOutputSchema,
  smartlistListInputSchema,
  smartlistListOutputSchema,
  smartlistCreateInputSchema,
  smartlistCreateOutputSchema,
  smartlistPatchInputSchema,
  smartlistPatchOutputSchema,
  smartlistDeleteInputSchema,
  smartlistDeleteOutputSchema,
  taskCompleteInputSchema,
  taskCompleteOutputSchema,
  taskDeleteInputSchema,
  taskDeleteOutputSchema,
  taskMoveToListInputSchema,
  taskMoveToListOutputSchema,
  taskMoveToProjectInputSchema,
  taskMoveToProjectOutputSchema,
  taskPatchInputSchema,
  taskPatchOutputSchema,
  taskSearchInputSchema,
  taskSearchOutputSchema,
  taskUncompleteInputSchema,
  taskUncompleteOutputSchema,
} from "@freeanima/shared/sap-contract/frames/task";

import { defineHubMethod, dualTransportMeta } from "@freeanima/shared/hub-contract";

export const taskMethodDefs = {
  "tasklist.list": defineHubMethod({
    input: tasklistListInputSchema,
    output: tasklistListOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "tasklist.create": defineHubMethod({
    input: tasklistCreateInputSchema,
    output: tasklistCreateOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "tasklist.patch": defineHubMethod({
    input: tasklistPatchInputSchema,
    output: tasklistPatchOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "tasklist.delete": defineHubMethod({
    input: tasklistDeleteInputSchema,
    output: tasklistDeleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "tasklist.item.list": defineHubMethod({
    input: tasklistItemListInputSchema,
    output: tasklistItemListOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "tasklist.item.create": defineHubMethod({
    input: tasklistItemCreateInputSchema,
    output: tasklistItemCreateOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "smartlist.list": defineHubMethod({
    input: smartlistListInputSchema,
    output: smartlistListOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "smartlist.create": defineHubMethod({
    input: smartlistCreateInputSchema,
    output: smartlistCreateOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "smartlist.patch": defineHubMethod({
    input: smartlistPatchInputSchema,
    output: smartlistPatchOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "smartlist.delete": defineHubMethod({
    input: smartlistDeleteInputSchema,
    output: smartlistDeleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "project.item.list": defineHubMethod({
    input: projectItemListInputSchema,
    output: projectItemListOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "project.item.create": defineHubMethod({
    input: projectItemCreateInputSchema,
    output: projectItemCreateOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.patch": defineHubMethod({
    input: taskPatchInputSchema,
    output: taskPatchOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.moveToProject": defineHubMethod({
    input: taskMoveToProjectInputSchema,
    output: taskMoveToProjectOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.moveToList": defineHubMethod({
    input: taskMoveToListInputSchema,
    output: taskMoveToListOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.complete": defineHubMethod({
    input: taskCompleteInputSchema,
    output: taskCompleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.uncomplete": defineHubMethod({
    input: taskUncompleteInputSchema,
    output: taskUncompleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.delete": defineHubMethod({
    input: taskDeleteInputSchema,
    output: taskDeleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.search": defineHubMethod({
    input: taskSearchInputSchema,
    output: taskSearchOutputSchema,
    meta: dualTransportMeta(true),
  }),
} as const;
