/** @deprecated 请从 `@freeanima/habitat/core/llm/auto-llm-prompt` 导入；此处 re-export 兼容旧路径 */
export {
  AUTO_LLM_PROTOCOL_BODY,
  AUTO_LLM_PROTOCOL_FRAME,
  AUTO_LLM_DEFAULT_MAX_DURATION_MS,
  AUTO_LLM_CHAT_DEFAULT_MAX_DURATION_MS,
  composeAutoLlmPrompt,
  composedAutoLlmPromptToChatMessages,
  formatAutoLlmProtocol,
  formatAutoLlmTaskSpec,
  formatAutoLlmTaskParamsBody,
  formatAutoLlmTaskParamsMessage,
  formatAutoLlmSkillsMessage,
  formatAutoLlmDataPart,
  formatCronAutoLlmTaskSpec,
  formatCronAutoLlmTaskSection,
  buildAutoLlmSystemPrompt,
  type AutoLlmDataPart,
  type AutoLlmTaskParams,
  type ComposeAutoLlmPromptInput,
  type ComposedAutoLlmPrompt,
} from "@freeanima/habitat/core/llm/auto-llm-prompt";
