/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as SidebarRouteRouteImport } from './routes/_sidebar/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopPathRouteImport } from './routes/workshop/$path'
import { Route as SidebarWorldsRouteImport } from './routes/_sidebar/worlds'
import { Route as SidebarToolsRouteImport } from './routes/_sidebar/tools'
import { Route as SidebarSystemPromptRouteImport } from './routes/_sidebar/system-prompt'
import { Route as SidebarSubjectsRouteImport } from './routes/_sidebar/subjects'
import { Route as SidebarSleepRouteImport } from './routes/_sidebar/sleep'
import { Route as SidebarSemanticMemoryRouteImport } from './routes/_sidebar/semantic-memory'
import { Route as SidebarSelfLayerRouteImport } from './routes/_sidebar/self-layer'
import { Route as SidebarSatellitesRouteImport } from './routes/_sidebar/satellites'
import { Route as SidebarMemoryRouteImport } from './routes/_sidebar/memory'
import { Route as SidebarMcpRouteImport } from './routes/_sidebar/mcp'
import { Route as SidebarLimbicMemoryRouteImport } from './routes/_sidebar/limbic-memory'
import { Route as SidebarFtsRouteImport } from './routes/_sidebar/fts'
import { Route as SidebarDreamRouteImport } from './routes/_sidebar/dream'
import { Route as SidebarDashboardRouteImport } from './routes/_sidebar/dashboard'
import { Route as SidebarCronRouteImport } from './routes/_sidebar/cron'
import { Route as SidebarCredentialsRouteImport } from './routes/_sidebar/credentials'
import { Route as SidebarConfigRouteImport } from './routes/_sidebar/config'
import { Route as SidebarCommandsRouteImport } from './routes/_sidebar/commands'
import { Route as SidebarAutobiographicalMemoryRouteImport } from './routes/_sidebar/autobiographical-memory'
import { Route as SidebarAutoLlmRunsRouteImport } from './routes/_sidebar/auto-llm-runs'
import { Route as SidebarAcpRouteImport } from './routes/_sidebar/acp'
import { Route as SidebarConversationsRouteRouteImport } from './routes/_sidebar/conversations/route'
import { Route as SidebarConversationsIndexRouteImport } from './routes/_sidebar/conversations/index'
import { Route as SidebarConversationsConversationIdRouteImport } from './routes/_sidebar/conversations/$conversationId'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopPathRoute = WorkshopPathRouteImport.update({
  id: '/$path',
  path: '/$path',
  getParentRoute: () => WorkshopRoute,
} as any)
const SidebarWorldsRoute = SidebarWorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarToolsRoute = SidebarToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSystemPromptRoute = SidebarSystemPromptRouteImport.update({
  id: '/system-prompt',
  path: '/system-prompt',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSubjectsRoute = SidebarSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSleepRoute = SidebarSleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSemanticMemoryRoute = SidebarSemanticMemoryRouteImport.update({
  id: '/semantic-memory',
  path: '/semantic-memory',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSelfLayerRoute = SidebarSelfLayerRouteImport.update({
  id: '/self-layer',
  path: '/self-layer',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSatellitesRoute = SidebarSatellitesRouteImport.update({
  id: '/satellites',
  path: '/satellites',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarMemoryRoute = SidebarMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarMcpRoute = SidebarMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarLimbicMemoryRoute = SidebarLimbicMemoryRouteImport.update({
  id: '/limbic-memory',
  path: '/limbic-memory',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarFtsRoute = SidebarFtsRouteImport.update({
  id: '/fts',
  path: '/fts',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDreamRoute = SidebarDreamRouteImport.update({
  id: '/dream',
  path: '/dream',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDashboardRoute = SidebarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarCronRoute = SidebarCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarCredentialsRoute = SidebarCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConfigRoute = SidebarConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarCommandsRoute = SidebarCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAutobiographicalMemoryRoute =
  SidebarAutobiographicalMemoryRouteImport.update({
    id: '/autobiographical-memory',
    path: '/autobiographical-memory',
    getParentRoute: () => SidebarRouteRoute,
  } as any)
const SidebarAutoLlmRunsRoute = SidebarAutoLlmRunsRouteImport.update({
  id: '/auto-llm-runs',
  path: '/auto-llm-runs',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAcpRoute = SidebarAcpRouteImport.update({
  id: '/acp',
  path: '/acp',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConversationsRouteRoute =
  SidebarConversationsRouteRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => SidebarRouteRoute,
  } as any)
const SidebarConversationsIndexRoute =
  SidebarConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarConversationsRouteRoute,
  } as any)
const SidebarConversationsConversationIdRoute =
  SidebarConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => SidebarConversationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/conversations': typeof SidebarConversationsRouteRouteWithChildren
  '/acp': typeof SidebarAcpRoute
  '/auto-llm-runs': typeof SidebarAutoLlmRunsRoute
  '/autobiographical-memory': typeof SidebarAutobiographicalMemoryRoute
  '/commands': typeof SidebarCommandsRoute
  '/config': typeof SidebarConfigRoute
  '/credentials': typeof SidebarCredentialsRoute
  '/cron': typeof SidebarCronRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/dream': typeof SidebarDreamRoute
  '/fts': typeof SidebarFtsRoute
  '/limbic-memory': typeof SidebarLimbicMemoryRoute
  '/mcp': typeof SidebarMcpRoute
  '/memory': typeof SidebarMemoryRoute
  '/satellites': typeof SidebarSatellitesRoute
  '/self-layer': typeof SidebarSelfLayerRoute
  '/semantic-memory': typeof SidebarSemanticMemoryRoute
  '/sleep': typeof SidebarSleepRoute
  '/subjects': typeof SidebarSubjectsRoute
  '/system-prompt': typeof SidebarSystemPromptRoute
  '/tools': typeof SidebarToolsRoute
  '/worlds': typeof SidebarWorldsRoute
  '/workshop/$path': typeof WorkshopPathRoute
  '/conversations/$conversationId': typeof SidebarConversationsConversationIdRoute
  '/conversations/': typeof SidebarConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/acp': typeof SidebarAcpRoute
  '/auto-llm-runs': typeof SidebarAutoLlmRunsRoute
  '/autobiographical-memory': typeof SidebarAutobiographicalMemoryRoute
  '/commands': typeof SidebarCommandsRoute
  '/config': typeof SidebarConfigRoute
  '/credentials': typeof SidebarCredentialsRoute
  '/cron': typeof SidebarCronRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/dream': typeof SidebarDreamRoute
  '/fts': typeof SidebarFtsRoute
  '/limbic-memory': typeof SidebarLimbicMemoryRoute
  '/mcp': typeof SidebarMcpRoute
  '/memory': typeof SidebarMemoryRoute
  '/satellites': typeof SidebarSatellitesRoute
  '/self-layer': typeof SidebarSelfLayerRoute
  '/semantic-memory': typeof SidebarSemanticMemoryRoute
  '/sleep': typeof SidebarSleepRoute
  '/subjects': typeof SidebarSubjectsRoute
  '/system-prompt': typeof SidebarSystemPromptRoute
  '/tools': typeof SidebarToolsRoute
  '/worlds': typeof SidebarWorldsRoute
  '/workshop/$path': typeof WorkshopPathRoute
  '/conversations/$conversationId': typeof SidebarConversationsConversationIdRoute
  '/conversations': typeof SidebarConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/workshop': typeof WorkshopRouteWithChildren
  '/_sidebar/conversations': typeof SidebarConversationsRouteRouteWithChildren
  '/_sidebar/acp': typeof SidebarAcpRoute
  '/_sidebar/auto-llm-runs': typeof SidebarAutoLlmRunsRoute
  '/_sidebar/autobiographical-memory': typeof SidebarAutobiographicalMemoryRoute
  '/_sidebar/commands': typeof SidebarCommandsRoute
  '/_sidebar/config': typeof SidebarConfigRoute
  '/_sidebar/credentials': typeof SidebarCredentialsRoute
  '/_sidebar/cron': typeof SidebarCronRoute
  '/_sidebar/dashboard': typeof SidebarDashboardRoute
  '/_sidebar/dream': typeof SidebarDreamRoute
  '/_sidebar/fts': typeof SidebarFtsRoute
  '/_sidebar/limbic-memory': typeof SidebarLimbicMemoryRoute
  '/_sidebar/mcp': typeof SidebarMcpRoute
  '/_sidebar/memory': typeof SidebarMemoryRoute
  '/_sidebar/satellites': typeof SidebarSatellitesRoute
  '/_sidebar/self-layer': typeof SidebarSelfLayerRoute
  '/_sidebar/semantic-memory': typeof SidebarSemanticMemoryRoute
  '/_sidebar/sleep': typeof SidebarSleepRoute
  '/_sidebar/subjects': typeof SidebarSubjectsRoute
  '/_sidebar/system-prompt': typeof SidebarSystemPromptRoute
  '/_sidebar/tools': typeof SidebarToolsRoute
  '/_sidebar/worlds': typeof SidebarWorldsRoute
  '/workshop/$path': typeof WorkshopPathRoute
  '/_sidebar/conversations/$conversationId': typeof SidebarConversationsConversationIdRoute
  '/_sidebar/conversations/': typeof SidebarConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workshop'
    | '/conversations'
    | '/acp'
    | '/auto-llm-runs'
    | '/autobiographical-memory'
    | '/commands'
    | '/config'
    | '/credentials'
    | '/cron'
    | '/dashboard'
    | '/dream'
    | '/fts'
    | '/limbic-memory'
    | '/mcp'
    | '/memory'
    | '/satellites'
    | '/self-layer'
    | '/semantic-memory'
    | '/sleep'
    | '/subjects'
    | '/system-prompt'
    | '/tools'
    | '/worlds'
    | '/workshop/$path'
    | '/conversations/$conversationId'
    | '/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workshop'
    | '/acp'
    | '/auto-llm-runs'
    | '/autobiographical-memory'
    | '/commands'
    | '/config'
    | '/credentials'
    | '/cron'
    | '/dashboard'
    | '/dream'
    | '/fts'
    | '/limbic-memory'
    | '/mcp'
    | '/memory'
    | '/satellites'
    | '/self-layer'
    | '/semantic-memory'
    | '/sleep'
    | '/subjects'
    | '/system-prompt'
    | '/tools'
    | '/worlds'
    | '/workshop/$path'
    | '/conversations/$conversationId'
    | '/conversations'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/workshop'
    | '/_sidebar/conversations'
    | '/_sidebar/acp'
    | '/_sidebar/auto-llm-runs'
    | '/_sidebar/autobiographical-memory'
    | '/_sidebar/commands'
    | '/_sidebar/config'
    | '/_sidebar/credentials'
    | '/_sidebar/cron'
    | '/_sidebar/dashboard'
    | '/_sidebar/dream'
    | '/_sidebar/fts'
    | '/_sidebar/limbic-memory'
    | '/_sidebar/mcp'
    | '/_sidebar/memory'
    | '/_sidebar/satellites'
    | '/_sidebar/self-layer'
    | '/_sidebar/semantic-memory'
    | '/_sidebar/sleep'
    | '/_sidebar/subjects'
    | '/_sidebar/system-prompt'
    | '/_sidebar/tools'
    | '/_sidebar/worlds'
    | '/workshop/$path'
    | '/_sidebar/conversations/$conversationId'
    | '/_sidebar/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
  WorkshopRoute: typeof WorkshopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop/$path': {
      id: '/workshop/$path'
      path: '/$path'
      fullPath: '/workshop/$path'
      preLoaderRoute: typeof WorkshopPathRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/_sidebar/worlds': {
      id: '/_sidebar/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof SidebarWorldsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/tools': {
      id: '/_sidebar/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof SidebarToolsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/system-prompt': {
      id: '/_sidebar/system-prompt'
      path: '/system-prompt'
      fullPath: '/system-prompt'
      preLoaderRoute: typeof SidebarSystemPromptRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/subjects': {
      id: '/_sidebar/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SidebarSubjectsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/sleep': {
      id: '/_sidebar/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SidebarSleepRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/semantic-memory': {
      id: '/_sidebar/semantic-memory'
      path: '/semantic-memory'
      fullPath: '/semantic-memory'
      preLoaderRoute: typeof SidebarSemanticMemoryRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/self-layer': {
      id: '/_sidebar/self-layer'
      path: '/self-layer'
      fullPath: '/self-layer'
      preLoaderRoute: typeof SidebarSelfLayerRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/satellites': {
      id: '/_sidebar/satellites'
      path: '/satellites'
      fullPath: '/satellites'
      preLoaderRoute: typeof SidebarSatellitesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/memory': {
      id: '/_sidebar/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof SidebarMemoryRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/mcp': {
      id: '/_sidebar/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof SidebarMcpRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/limbic-memory': {
      id: '/_sidebar/limbic-memory'
      path: '/limbic-memory'
      fullPath: '/limbic-memory'
      preLoaderRoute: typeof SidebarLimbicMemoryRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/fts': {
      id: '/_sidebar/fts'
      path: '/fts'
      fullPath: '/fts'
      preLoaderRoute: typeof SidebarFtsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dream': {
      id: '/_sidebar/dream'
      path: '/dream'
      fullPath: '/dream'
      preLoaderRoute: typeof SidebarDreamRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboard': {
      id: '/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/cron': {
      id: '/_sidebar/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof SidebarCronRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/credentials': {
      id: '/_sidebar/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof SidebarCredentialsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/config': {
      id: '/_sidebar/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof SidebarConfigRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/commands': {
      id: '/_sidebar/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof SidebarCommandsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/autobiographical-memory': {
      id: '/_sidebar/autobiographical-memory'
      path: '/autobiographical-memory'
      fullPath: '/autobiographical-memory'
      preLoaderRoute: typeof SidebarAutobiographicalMemoryRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/auto-llm-runs': {
      id: '/_sidebar/auto-llm-runs'
      path: '/auto-llm-runs'
      fullPath: '/auto-llm-runs'
      preLoaderRoute: typeof SidebarAutoLlmRunsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/acp': {
      id: '/_sidebar/acp'
      path: '/acp'
      fullPath: '/acp'
      preLoaderRoute: typeof SidebarAcpRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/conversations': {
      id: '/_sidebar/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof SidebarConversationsRouteRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/conversations/': {
      id: '/_sidebar/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof SidebarConversationsIndexRouteImport
      parentRoute: typeof SidebarConversationsRouteRoute
    }
    '/_sidebar/conversations/$conversationId': {
      id: '/_sidebar/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof SidebarConversationsConversationIdRouteImport
      parentRoute: typeof SidebarConversationsRouteRoute
    }
  }
}

interface SidebarConversationsRouteRouteChildren {
  SidebarConversationsConversationIdRoute: typeof SidebarConversationsConversationIdRoute
  SidebarConversationsIndexRoute: typeof SidebarConversationsIndexRoute
}

const SidebarConversationsRouteRouteChildren: SidebarConversationsRouteRouteChildren =
  {
    SidebarConversationsConversationIdRoute:
      SidebarConversationsConversationIdRoute,
    SidebarConversationsIndexRoute: SidebarConversationsIndexRoute,
  }

const SidebarConversationsRouteRouteWithChildren =
  SidebarConversationsRouteRoute._addFileChildren(
    SidebarConversationsRouteRouteChildren,
  )

interface SidebarRouteRouteChildren {
  SidebarConversationsRouteRoute: typeof SidebarConversationsRouteRouteWithChildren
  SidebarAcpRoute: typeof SidebarAcpRoute
  SidebarAutoLlmRunsRoute: typeof SidebarAutoLlmRunsRoute
  SidebarAutobiographicalMemoryRoute: typeof SidebarAutobiographicalMemoryRoute
  SidebarCommandsRoute: typeof SidebarCommandsRoute
  SidebarConfigRoute: typeof SidebarConfigRoute
  SidebarCredentialsRoute: typeof SidebarCredentialsRoute
  SidebarCronRoute: typeof SidebarCronRoute
  SidebarDashboardRoute: typeof SidebarDashboardRoute
  SidebarDreamRoute: typeof SidebarDreamRoute
  SidebarFtsRoute: typeof SidebarFtsRoute
  SidebarLimbicMemoryRoute: typeof SidebarLimbicMemoryRoute
  SidebarMcpRoute: typeof SidebarMcpRoute
  SidebarMemoryRoute: typeof SidebarMemoryRoute
  SidebarSatellitesRoute: typeof SidebarSatellitesRoute
  SidebarSelfLayerRoute: typeof SidebarSelfLayerRoute
  SidebarSemanticMemoryRoute: typeof SidebarSemanticMemoryRoute
  SidebarSleepRoute: typeof SidebarSleepRoute
  SidebarSubjectsRoute: typeof SidebarSubjectsRoute
  SidebarSystemPromptRoute: typeof SidebarSystemPromptRoute
  SidebarToolsRoute: typeof SidebarToolsRoute
  SidebarWorldsRoute: typeof SidebarWorldsRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarConversationsRouteRoute: SidebarConversationsRouteRouteWithChildren,
  SidebarAcpRoute: SidebarAcpRoute,
  SidebarAutoLlmRunsRoute: SidebarAutoLlmRunsRoute,
  SidebarAutobiographicalMemoryRoute: SidebarAutobiographicalMemoryRoute,
  SidebarCommandsRoute: SidebarCommandsRoute,
  SidebarConfigRoute: SidebarConfigRoute,
  SidebarCredentialsRoute: SidebarCredentialsRoute,
  SidebarCronRoute: SidebarCronRoute,
  SidebarDashboardRoute: SidebarDashboardRoute,
  SidebarDreamRoute: SidebarDreamRoute,
  SidebarFtsRoute: SidebarFtsRoute,
  SidebarLimbicMemoryRoute: SidebarLimbicMemoryRoute,
  SidebarMcpRoute: SidebarMcpRoute,
  SidebarMemoryRoute: SidebarMemoryRoute,
  SidebarSatellitesRoute: SidebarSatellitesRoute,
  SidebarSelfLayerRoute: SidebarSelfLayerRoute,
  SidebarSemanticMemoryRoute: SidebarSemanticMemoryRoute,
  SidebarSleepRoute: SidebarSleepRoute,
  SidebarSubjectsRoute: SidebarSubjectsRoute,
  SidebarSystemPromptRoute: SidebarSystemPromptRoute,
  SidebarToolsRoute: SidebarToolsRoute,
  SidebarWorldsRoute: SidebarWorldsRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

interface WorkshopRouteChildren {
  WorkshopPathRoute: typeof WorkshopPathRoute
}

const WorkshopRouteChildren: WorkshopRouteChildren = {
  WorkshopPathRoute: WorkshopPathRoute,
}

const WorkshopRouteWithChildren = WorkshopRoute._addFileChildren(
  WorkshopRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
  WorkshopRoute: WorkshopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
