import type { ToolSetRegistry } from "@freeanima/host/core/tool";
import type { StoredMessage } from "@freeanima/host/core/db/domain";
import {
  appendMessage,
  appendConversationMeta,
  appendUserTurn,
  getMaxMessagePos,
  findUserMessageByClientOpId,
  getLastMessageRole,
  assertConversationPlatform,
  cleanupDebugConversations,
  countMessages,
  countUserMessages,
  countConversationsByPlatform,
  findConversationByOrigin,
  activateConversationOrigin,
  getConversationCwd,
  getConversationTitle,
  initConversation,
  load,
  loadForRuntime,
  loadMessagePage,
  loadMessagesBeforePos,
  loadConversationMeta,
  loadConversationTools,
  listConversationSummaries,
  listConversationSummariesPage,
  listConversations,
  newConversation,
  patchConversationOrigin,
  rebuildConversationSystemPrompt,
  refreshSystemPromptOnResume,
  ensureSystemPromptFresh,
  rebuildConversationCache,
  rollbackToLastUser,
  rollbackBeforeLastUser,
  conversationExists,
  setConversationCwd,
  setConversationTitle,
  archiveConversation,
  unarchiveConversation,
  deleteUserConversation,
  updateConversationMeta,
  updateConversationMetaField,
} from "./conversation.ts";
import {
  advanceCompressionMeta,
  maybeApplyEmergencyCompression,
  recompressConversation,
  summarizeConversation,
} from "../turn/compression-orchestration.ts";
import {
  beginTurn,
  beginTurnFast,
  beginTurnPrepare,
  buildRuntimeMessages,
  finishTurn,
  repairAndPersistToolLoop,
  retryTurn,
} from "../turn/turn-runtime.ts";

/** Bound conversation/turn API for composition root */
export function createConversationService(tools: ToolSetRegistry) {
  return {
    tools,
    loadConversationTools: (
      conversationId: string,
      cachedMeta?: Parameters<typeof loadConversationTools>[2],
    ) => loadConversationTools(tools, conversationId, cachedMeta),
    loadConversationMeta,
    countConversationsByPlatform,
    listConversationSummaries,
    listConversationSummariesPage,
    listConversations,
    conversationExists,
    load,
    loadMessagePage,
    loadMessagesBeforePos,
    countMessages,
    countUserMessages,
    loadForRuntime,
    appendMessage: (msg: StoredMessage, conversation: string) => appendMessage(msg, conversation),
    appendConversationMeta,
    initConversation: (sid: string, model: string, opts: Parameters<typeof initConversation>[3]) =>
      initConversation(tools, sid, model, opts),
    newConversation: (platform: string, model?: string, platformExtra?: Record<string, unknown>) =>
      newConversation(tools, platform, model, platformExtra),
    findConversationByOrigin,
    activateConversationOrigin,
    updateConversationMetaField: (
      conversationId: string,
      patch: Parameters<typeof updateConversationMetaField>[1],
    ) => updateConversationMetaField(conversationId, patch),
    patchConversationOrigin,
    rebuildConversationSystemPrompt,
    rebuildConversationCache: (conversationId: string) =>
      rebuildConversationCache(tools, conversationId),
    ensureSystemPromptFresh,
    refreshSystemPromptOnResume,
    assertConversationPlatform,
    appendUserTurn,
    getMaxMessagePos: (conversationId: string) => getMaxMessagePos(conversationId),
    findUserMessageByClientOpId: (conversationId: string, client_op_id: string) =>
      findUserMessageByClientOpId(conversationId, client_op_id),
    getLastMessageRole: (conversationId: string) => getLastMessageRole(conversationId),
    advanceCompressionMeta: (
      conversationId: string,
      preloaded?: Parameters<typeof advanceCompressionMeta>[2],
    ) => advanceCompressionMeta(tools, conversationId, preloaded),
    recompressConversation: (
      conversationId: string,
      opts?: Parameters<typeof recompressConversation>[2],
      preloaded?: Parameters<typeof recompressConversation>[3],
    ) => recompressConversation(tools, conversationId, opts, preloaded),
    summarizeConversation: (
      conversationId: string,
      preloaded?: Parameters<typeof summarizeConversation>[2],
    ) => summarizeConversation(tools, conversationId, preloaded),
    repairAndPersistToolLoop,
    maybeApplyEmergencyCompression,
    buildRuntimeMessages: (conversationId: string) => buildRuntimeMessages(tools, conversationId),
    beginTurn: (conversationId: string, userText: string) =>
      beginTurn(tools, conversationId, userText),
    beginTurnFast,
    beginTurnPrepare: (conversationId: string) => beginTurnPrepare(tools, conversationId),
    finishTurn: (
      conversationId: string,
      messages: StoredMessage[],
      userText: string,
      model: string,
      functions?: string[],
      skipMessageAppend?: boolean,
    ) => finishTurn(tools, conversationId, messages, userText, model, functions, skipMessageAppend),
    updateConversationMeta: (
      conversationId: string,
      model: string,
      opts?: Parameters<typeof updateConversationMeta>[3],
    ) => updateConversationMeta(tools, conversationId, model, opts),
    setConversationTitle,
    archiveConversation,
    unarchiveConversation,
    deleteUserConversation,
    getConversationTitle,
    getConversationCwd,
    setConversationCwd,
    rollbackToLastUser,
    rollbackBeforeLastUser,
    retryTurn: (conversationId: string) => retryTurn(tools, conversationId),
    cleanupDebugConversations,
  };
}

export type ConversationService = ReturnType<typeof createConversationService>;
