export {
  RPC_PROTOCOL_VERSION,
  parseRpcEnvelope,
  serializeRpcEnvelope,
  habitatRpcConnectPayloadSchema,
  habitatRpcConnectedPayloadSchema,
  HABITAT_RPC_VERSION,
} from "./protocol.ts";
export type { RpcEnvelope, RpcProtocolError } from "./protocol.ts";
export { randomUuid } from "@freeanima/host/kernel/random-uuid.ts";

export {
  normalizeAppSlug,
  normalizeInstanceId,
  formatRemoteToolName,
  formatRemoteToolNameAlias,
  parseRemoteToolName,
  isRemotePrefixedToolName,
  remoteToolsetId,
  formatRemotePlatform,
  resolveDefaultRemotePlatform,
  isRemotePlatform,
  parseRemotePlatform,
  isValidRemoteInstanceId,
  REMOTE_INSTANCE_ID_PATTERN,
} from "./naming.ts";
export type { ParsedRemoteToolName, ParsedRemotePlatform } from "./naming.ts";

export { generateRemoteInstanceIdCandidate, assertRemoteInstanceId } from "./instance-id.ts";

export {
  browserRemoteInstanceStore,
  memoryRemoteInstanceStore,
  loadRemoteInstanceId,
  type RemoteInstanceStore,
} from "./instance-store.ts";
export {
  remoteToolsAttachPayloadSchema,
  remoteToolsAttachOutputSchema,
  remoteToolsDetachPayloadSchema,
  remoteToolsDetachOutputSchema,
  heartbeatPayloadSchema,
} from "./frames/lifecycle.ts";
export type {
  RemoteToolsAttachPayload,
  RemoteToolsAttachOutput,
  RemoteToolsDetachPayload,
  RemoteToolsDetachOutput,
  HeartbeatPayload,
} from "./frames/lifecycle.ts";

export {
  conversationCreateInputSchema,
  conversationCreateOutputSchema,
  conversationListInputSchema,
  conversationListOutputSchema,
  conversationMessagesInputSchema,
  conversationPatchTitleInputSchema,
  conversationArchiveInputSchema,
  conversationUnarchiveInputSchema,
  conversationDeleteInputSchema,
  conversationMutateOutputSchema,
  conversationSubscribeInputSchema,
  conversationSubscribeInboxInputSchema,
  conversationMarkReadInputSchema,
  conversationMarkReadOutputSchema,
  conversationUnreadCountInputSchema,
  conversationUnreadCountOutputSchema,
  conversationUpdatedPayloadSchema,
  conversationCommandsInputSchema,
  conversationCommandsOutputSchema,
  conversationCommandItemSchema,
  conversationCommandInputSchema,
  conversationCommandOutputSchema,
} from "./frames/conversation.ts";
export type {
  ConversationCreateInput,
  ConversationCreateOutput,
  ConversationListInput,
  ConversationListOutput,
  StoredMessagesInput,
  ConversationPatchTitleInput,
  ConversationArchiveInput,
  ConversationUnarchiveInput,
  ConversationDeleteInput,
  ConversationMutateOutput,
  ConversationSubscribeInput,
  ConversationSubscribeInboxInput,
  ConversationMarkReadInput,
  ConversationMarkReadOutput,
  ConversationUnreadCountInput,
  ConversationUnreadCountOutput,
  ConversationUpdatedPayload,
  ConversationCommandsInput,
  ConversationCommandsOutput,
  ConversationCommandItem,
  ConversationCommandInput,
  ConversationCommandOutput,
} from "./frames/conversation.ts";

export {
  taskListRowSchema,
  taskItemRowSchema,
  taskItemSearchFiltersSchema,
  smartListRowSchema,
  tasklistListInputSchema,
  tasklistListOutputSchema,
  tasklistStatsInputSchema,
  tasklistStatsOutputSchema,
  tasklistCreateInputSchema,
  tasklistCreateOutputSchema,
  tasklistPatchInputSchema,
  tasklistPatchOutputSchema,
  tasklistDeleteInputSchema,
  tasklistDeleteOutputSchema,
  smartlistListInputSchema,
  smartlistListOutputSchema,
  smartlistStatsInputSchema,
  smartlistStatsOutputSchema,
  smartlistCreateInputSchema,
  smartlistCreateOutputSchema,
  smartlistPatchInputSchema,
  smartlistPatchOutputSchema,
  smartlistDeleteInputSchema,
  smartlistDeleteOutputSchema,
  taskListInputSchema,
  taskListOutputSchema,
  tasklistItemListInputSchema,
  tasklistItemListOutputSchema,
  tasklistItemCreateInputSchema,
  tasklistItemCreateOutputSchema,
  projectItemListInputSchema,
  projectItemListOutputSchema,
  projectItemCreateInputSchema,
  projectItemCreateOutputSchema,
  taskCreateInputSchema,
  taskCreateOutputSchema,
  taskMoveToProjectInputSchema,
  taskMoveToProjectOutputSchema,
  taskMoveToListInputSchema,
  taskMoveToListOutputSchema,
  taskGetInputSchema,
  taskGetOutputSchema,
  taskPatchInputSchema,
  taskPatchOutputSchema,
  taskCompleteInputSchema,
  taskCompleteOutputSchema,
  taskUncompleteInputSchema,
  taskUncompleteOutputSchema,
  taskDeleteInputSchema,
  taskDeleteOutputSchema,
  taskSearchInputSchema,
  taskSearchOutputSchema,
} from "./frames/task.ts";
export type {
  TaskListRowPayload,
  TaskItemRowPayload,
  TaskItemSearchFiltersPayload,
  SmartListRowPayload,
  TasklistListInput,
  TasklistListOutput,
  TasklistStatsInput,
  TasklistStatsOutput,
  TasklistCreateInput,
  TasklistCreateOutput,
  TasklistPatchInput,
  TasklistPatchOutput,
  TasklistDeleteInput,
  TasklistDeleteOutput,
  SmartlistListInput,
  SmartlistListOutput,
  SmartlistStatsInput,
  SmartlistStatsOutput,
  SmartlistCreateInput,
  SmartlistCreateOutput,
  SmartlistPatchInput,
  SmartlistPatchOutput,
  SmartlistDeleteInput,
  SmartlistDeleteOutput,
  TaskListInput,
  TaskListOutput,
  TasklistItemListInput,
  TasklistItemListOutput,
  TasklistItemCreateInput,
  TasklistItemCreateOutput,
  ProjectItemListInput,
  ProjectItemListOutput,
  ProjectItemCreateInput,
  ProjectItemCreateOutput,
  TaskCreateInput,
  TaskCreateOutput,
  TaskMoveToProjectInput,
  TaskMoveToProjectOutput,
  TaskMoveToListInput,
  TaskMoveToListOutput,
  TaskGetInput,
  TaskGetOutput,
  TaskPatchInput,
  TaskPatchOutput,
  TaskCompleteInput,
  TaskCompleteOutput,
  TaskUncompleteInput,
  TaskUncompleteOutput,
  TaskDeleteInput,
  TaskDeleteOutput,
  TaskSearchInput,
  TaskSearchOutput,
} from "./frames/task.ts";

export {
  emailAccountRowSchema,
  emailMessageRowSchema,
  emailThreadRowSchema,
  emailAccountListInputSchema,
  emailAccountListOutputSchema,
  emailMessageListInputSchema,
  emailMessageListOutputSchema,
  emailMessageReadInputSchema,
  emailMessageReadOutputSchema,
  emailMessageMarkReadInputSchema,
  emailMessageMarkReadOutputSchema,
  emailMessageMarkUnreadInputSchema,
  emailMessageMarkUnreadOutputSchema,
  emailMessageDeleteInputSchema,
  emailMessageDeleteOutputSchema,
  emailSendInputSchema,
  emailSendOutputSchema,
  emailSyncInputSchema,
  emailSyncOutputSchema,
  emailThreadListInputSchema,
  emailThreadListOutputSchema,
  emailMessageSearchInputSchema,
  emailMessageSearchOutputSchema,
  emailProviderIdSchema,
  emailProviderPresetSchema,
  emailProviderListInputSchema,
  emailProviderListOutputSchema,
  emailAccountCreateInputSchema,
  emailAccountCreateOutputSchema,
  emailAccountPatchInputSchema,
  emailAccountPatchOutputSchema,
  emailAccountDeleteInputSchema,
  emailAccountDeleteOutputSchema,
  emailDraftSaveInputSchema,
  emailDraftSaveOutputSchema,
  emailDraftSendInputSchema,
  emailDraftSendOutputSchema,
  emailMailboxCreateInputSchema,
  emailMailboxCreateOutputSchema,
  emailMailboxDeleteInputSchema,
  emailMailboxDeleteOutputSchema,
  emailMailboxInfoSchema,
  emailMailboxListInputSchema,
  emailMailboxListOutputSchema,
  emailMailboxRenameInputSchema,
  emailMailboxRenameOutputSchema,
  emailMessageMoveInputSchema,
  emailMessageMoveOutputSchema,
  emailMessageMarkFlaggedInputSchema,
  emailMessageMarkFlaggedOutputSchema,
  emailMessageMarkUnflaggedInputSchema,
  emailMessageMarkUnflaggedOutputSchema,
} from "./frames/email.ts";
export type {
  EmailAccountRowPayload,
  EmailMessageRowPayload,
  EmailThreadRowPayload,
  EmailAccountListInput,
  EmailAccountListOutput,
  EmailMessageListInput,
  EmailMessageListOutput,
  EmailMessageReadInput,
  EmailMessageReadOutput,
  EmailMessageMarkReadInput,
  EmailMessageMarkReadOutput,
  EmailMessageMarkUnreadInput,
  EmailMessageMarkUnreadOutput,
  EmailMessageDeleteInput,
  EmailMessageDeleteOutput,
  EmailSendInput,
  EmailSendOutput,
  EmailMessageSearchInput,
  EmailMessageSearchOutput,
  EmailSyncInput,
  EmailSyncOutput,
  EmailThreadListInput,
  EmailThreadListOutput,
  EmailProviderId,
  EmailProviderPresetPayload,
  EmailProviderListInput,
  EmailProviderListOutput,
  EmailAccountCreateInput,
  EmailAccountCreateOutput,
  EmailAccountPatchInput,
  EmailAccountPatchOutput,
  EmailAccountDeleteInput,
  EmailAccountDeleteOutput,
  EmailDraftSaveInput,
  EmailDraftSaveOutput,
  EmailDraftSendInput,
  EmailDraftSendOutput,
  EmailMailboxCreateInput,
  EmailMailboxCreateOutput,
  EmailMailboxDeleteInput,
  EmailMailboxDeleteOutput,
  EmailMailboxListInput,
  EmailMailboxListOutput,
  EmailMailboxRenameInput,
  EmailMailboxRenameOutput,
  EmailMessageMoveInput,
  EmailMessageMoveOutput,
  EmailMessageMarkFlaggedInput,
  EmailMessageMarkFlaggedOutput,
  EmailMessageMarkUnflaggedInput,
  EmailMessageMarkUnflaggedOutput,
} from "./frames/email.ts";

export {
  notificationRecipientKindSchema,
  notificationReadFilterSchema,
  notificationSourceKindSchema,
  notificationRowSchema,
  notificationListInputSchema,
  notificationListOutputSchema,
  notificationMarkReadInputSchema,
  notificationMarkReadOutputSchema,
  notificationRecipientsOutputSchema,
  notificationSubscribeInboxInputSchema,
  notificationSubscribeInboxOutputSchema,
  notificationCreatedEventSchema,
} from "./frames/notification.ts";
export type {
  NotificationRecipientKind,
  NotificationReadFilter,
  NotificationSourceKind,
  NotificationRow,
  NotificationListInput,
  NotificationListOutput,
  NotificationMarkReadInput,
  NotificationMarkReadOutput,
  NotificationRecipientsOutput,
  NotificationSubscribeInboxInput,
  NotificationSubscribeInboxOutput,
  NotificationCreatedEvent,
} from "./frames/notification.ts";

export {
  diaryEntryRowSchema,
  diaryTextBlockSchema,
  diaryListInputSchema,
  diaryListOutputSchema,
  diaryCreateInputSchema,
  diaryCreateOutputSchema,
  diaryAppendInputSchema,
  diaryAppendOutputSchema,
  diaryPatchInputSchema,
  diaryPatchOutputSchema,
  diaryDeleteInputSchema,
  diaryDeleteOutputSchema,
  diaryGetInputSchema,
  diaryGetOutputSchema,
  diarySearchInputSchema,
  diarySearchOutputSchema,
  diaryBlockCreateInputSchema,
  diaryBlockCreateOutputSchema,
  diaryBlockPatchInputSchema,
  diaryBlockPatchOutputSchema,
  diaryBlockDeleteInputSchema,
  diaryBlockDeleteOutputSchema,
  diaryBlockReorderInputSchema,
  diaryBlockReorderOutputSchema,
  diaryBlockTemplatePresetSchema,
  diaryBlockTemplateRowSchema,
  diaryTemplateListInputSchema,
  diaryTemplateListOutputSchema,
  diaryTemplateCreateInputSchema,
  diaryTemplateCreateOutputSchema,
  diaryTemplatePatchInputSchema,
  diaryTemplatePatchOutputSchema,
  diaryTemplateDeleteInputSchema,
  diaryTemplateDeleteOutputSchema,
  diarySuggestTagsInputSchema,
  diarySuggestTagsOutputSchema,
} from "./frames/diary.ts";
export type {
  DiaryEntryRowPayload,
  DiaryTextBlockPayload,
  DiaryListInput,
  DiaryListOutput,
  DiaryCreateInput,
  DiaryCreateOutput,
  DiaryAppendInput,
  DiaryAppendOutput,
  DiaryPatchInput,
  DiaryPatchOutput,
  DiaryDeleteInput,
  DiaryDeleteOutput,
  DiaryGetInput,
  DiaryGetOutput,
  DiarySearchInput,
  DiarySearchOutput,
  DiaryBlockCreateInput,
  DiaryBlockCreateOutput,
  DiaryBlockPatchInput,
  DiaryBlockPatchOutput,
  DiaryBlockDeleteInput,
  DiaryBlockDeleteOutput,
  DiaryBlockReorderInput,
  DiaryBlockReorderOutput,
  DiaryBlockTemplatePresetPayload,
  DiaryBlockTemplateRowPayload,
  DiaryTemplateListInput,
  DiaryTemplateListOutput,
  DiaryTemplateCreateInput,
  DiaryTemplateCreateOutput,
  DiaryTemplatePatchInput,
  DiaryTemplatePatchOutput,
  DiaryTemplateDeleteInput,
  DiaryTemplateDeleteOutput,
  DiarySuggestTagsInput,
  DiarySuggestTagsOutput,
} from "./frames/diary.ts";

export {
  vaultItemTypeSchema,
  vaultItemMetaRowSchema,
  vaultItemRowSchema,
  vaultItemDetailRowSchema,
  vaultSecretsViewSchema,
  vaultConfigRowSchema,
  vaultListInputSchema,
  vaultListOutputSchema,
  vaultGetInputSchema,
  vaultGetOutputSchema,
  vaultCreateInputSchema,
  vaultCreateOutputSchema,
  vaultCreatePlainInputSchema,
  vaultCreatePlainOutputSchema,
  vaultPatchInputSchema,
  vaultPatchOutputSchema,
  vaultPatchPlainInputSchema,
  vaultPatchPlainOutputSchema,
  vaultTouchInputSchema,
  vaultTouchOutputSchema,
  vaultDeleteInputSchema,
  vaultDeleteOutputSchema,
  vaultSearchInputSchema,
  vaultSearchOutputSchema,
  vaultCryptoGetInputSchema,
  vaultCryptoGetOutputSchema,
  vaultCryptoInitInputSchema,
  vaultCryptoInitOutputSchema,
  vaultCryptoChangeInputSchema,
  vaultCryptoChangeOutputSchema,
  vaultEnsureAgentInputSchema,
  vaultEnsureAgentOutputSchema,
  vaultResolveSecretUserInputSchema,
  vaultResolveSecretUserOutputSchema,
} from "./frames/vault.ts";
export type {
  VaultItemMetaRowPayload,
  VaultItemRowPayload,
  VaultItemDetailRowPayload,
  VaultSecretsViewPayload,
  VaultConfigRowPayload,
  VaultUriMatch,
  VaultUriEntryPayload,
  VaultListInput,
  VaultListOutput,
  VaultGetInput,
  VaultGetOutput,
  VaultCreateInput,
  VaultCreateOutput,
  VaultCreatePlainInput,
  VaultCreatePlainOutput,
  VaultPatchInput,
  VaultPatchOutput,
  VaultPatchPlainInput,
  VaultPatchPlainOutput,
  VaultTouchInput,
  VaultTouchOutput,
  VaultDeleteInput,
  VaultDeleteOutput,
  VaultSearchInput,
  VaultSearchOutput,
  VaultCryptoGetInput,
  VaultCryptoGetOutput,
  VaultCryptoInitInput,
  VaultCryptoInitOutput,
  VaultCryptoChangeInput,
  VaultCryptoChangeOutput,
  VaultEnsureAgentInput,
  VaultEnsureAgentOutput,
  VaultResolveSecretUserInput,
  VaultResolveSecretUserOutput,
} from "./frames/vault.ts";

export {
  messageSendInputSchema,
  messageSendOutputSchema,
  messageInterruptInputSchema,
  messageInterruptOutputSchema,
  streamAttachInputSchema,
  streamAttachOutputSchema,
  streamLookupInputSchema,
  streamLookupOutputSchema,
  llmDebugGetInputSchema,
  llmDebugGetOutputSchema,
  mapStreamApiEventToSap,
  mapRuntimeStreamEventToSap,
  mapSapStreamMethodToApi,
  streamEventMethods,
} from "./frames/message.ts";
export type {
  MessageSendInput,
  MessageSendOutput,
  MessageInterruptInput,
  MessageInterruptOutput,
  StreamAttachInput,
  StreamAttachOutput,
  StreamLookupInput,
  StreamLookupOutput,
  LlmDebugGetInput,
  LlmDebugGetOutput,
  StreamApiLikeEvent,
  StreamEventMethod,
} from "./frames/message.ts";

export {
  toolRegisterInputSchema,
  toolRegisterOutputSchema,
  toolUnregisterInputSchema,
  toolCallPayloadSchema,
  toolResultInputSchema,
  toolErrorInputSchema,
  sapToolDefInputSchema,
} from "./frames/tool.ts";
export type {
  ToolRegisterInput,
  ToolRegisterOutput,
  ToolUnregisterInput,
  ToolCallPayload,
  ToolResultInput,
  ToolErrorInput,
  RemoteToolDefInput,
} from "./frames/tool.ts";

export {
  terminalAttachInputSchema,
  terminalAttachOutputSchema,
  terminalWriteInputSchema,
  terminalResizeInputSchema,
  terminalCloseInputSchema,
  TERMINAL_EVENT_METHODS,
} from "./frames/terminal.ts";
export type {
  TerminalAttachInput,
  TerminalAttachOutput,
  TerminalWriteInput,
  TerminalResizeInput,
  TerminalCloseInput,
  TerminalEventMethod,
} from "./frames/terminal.ts";

export { defineRpcProtocolRouter, RPC_PROTOCOL_METHODS } from "./router.ts";
export type {
  RpcMethod,
  RpcRouterInputs,
  RpcRouterOutputs,
  RemoteToolsServerHandlers,
  RpcRequestAuthContext,
  RemoteToolsRequestContext,
  RpcStreamClient,
} from "./router.ts";

export {
  resolveHabitatHttpUrl,
  resolveHabitatRpcWsUrl,
  habitatHttpFromWsUrl,
  habitatHttpFromRpcWsUrl,
} from "./urls.ts";

export {
  getBundledRpcStreamClient,
  whenBundledRpcStreamClientReady,
  whenBundledRpcClientReady,
  createBundledSapStreamClient,
  resetBundledRpcStreamClientForTests,
  subscribeShellConfigChanges,
} from "./bundled-rpc-stream.ts";
export type { BundledSapStreamClient, SapConnectionState } from "./bundled-rpc-stream.ts";

export { sapClientFromRpc } from "./rpc-stream-client-from-rpc.ts";

export {
  createSapConversationStreamClient,
  sapListConversations,
  sapCreateConversation,
  sapGetStoredMessages,
  sapPatchConversationTitle,
  type SubscribeCallbacks,
  type SapSessionStreamClient,
} from "./conversation-stream-core.ts";

export {
  loadDirectOutpostConfig,
  formatDirectPlatform,
  defaultChatPlatform,
  type DirectOutpostConfig,
} from "./remote-tools-config.ts";

export {
  createRemoteToolsHabitatAttach,
  type CreateRemoteToolsAttachOptions,
  type RemoteToolsAttachHandle,
} from "./remote-tools-attach.ts";

export {
  hasNewAssistantReply,
  pollUntilAssistantReply,
  RECOVERY_INITIAL_DELAY_MS,
  RECOVERY_MAX_DELAY_MS,
  RECOVERY_MAX_DURATION_MS,
  type DisplayRecoveryItem,
} from "./display-recovery.ts";
