export type { StoredMessage as Message } from "./stored-message.ts";
export { isConversationMeta } from "./stored-message.ts";

export {
  allocateConversationCwd,
  loadConversationTools,
  loadConversationMeta,
  generateConversationId,
  countConversationsByPlatform,
  listConversationSummaries,
  listConversationSummariesPage,
  listConversations,
  conversationExists,
  load,
  loadMessagePage,
  countMessages,
  countUserMessages,
  loadForRuntime,
  appendMessage,
  appendConversationMeta,
  initConversation,
  newConversation,
  findConversationByOrigin,
  activateConversationOrigin,
  updateConversationMetaField,
  patchConversationOrigin,
  rebuildConversationSystemPrompt,
  rebuildConversationCache,
  refreshSystemPromptOnResume,
  assertConversationPlatform,
  appendUserTurn,
  updateConversationMeta,
  setConversationTitle,
  archiveConversation,
  unarchiveConversation,
  deleteUserConversation,
  getConversationTitle,
  getConversationCwd,
  setConversationCwd,
  rollbackToLastUser,
  cleanupDebugConversations,
  cleanupStaleConversations,
  STALE_SESSION_MIN_AGE_MS,
} from "./conversation-crud.ts";

export {
  flushCompressionSummaries,
  maybeApplyEmergencyCompression,
  advanceCompressionMeta,
  recompressConversation,
} from "@freeanima/runtime/turn";

export {
  repairAndPersistToolLoop,
  buildRuntimeMessages,
  beginTurn,
  beginTurnFast,
  beginTurnPrepare,
  finishTurn,
  retryTurn,
} from "@freeanima/runtime/turn";
