export * from "./types.ts";
export {
  getConversationMeta,
  upsertConversationMeta,
  patchConversationMeta,
  updateCompression,
  updateTodos,
  conversationExists,
  deleteConversation,
  archiveConversation,
  unarchiveConversation,
  listConversationIds,
  listDebugConversationIds,
  listConversationSummaries,
  listConversationSummariesPage,
  countConversationsByPlatform,
  deleteDebugConversations,
  findConversationIdByPlatformInfo,
  listConversationIdsMatchingPlatformProbe,
  getConversationMetaLite,
  getConversationTools,
  listConversationIdsUpdatedBetween,
  getEarliestConversationDay,
  listConversationActivityDays,
  listStaleConversationIdsForCleanup,
  deleteStaleConversations,
  isCronSession,
} from "./repos/conversation-repo.ts";
export {
  markConversationRead,
  countUnreadConversations,
  getConversationLastReadPos,
  conversationUnreadExistsSql,
} from "./repos/conversation-read-state-repo.ts";
export {
  aggregateUserActivityStats,
  emptyUserActivityStats,
  type ActivityWindowBound,
  type ActivityWindowCounts,
  type ActivityWindowId,
  type UserActivityStats,
} from "./repos/user-activity-stats-repo.ts";
export { purgeCronConversations } from "./repos/purge-cron-conversations.ts";
export {
  appendMessage,
  appendMessageReturningId,
  getMessageContentById,
  getMessageContentsByIds,
  getMessageTextItemsByIds,
  updateMessageContent,
  nextMessagePos,
  getMaxMessagePos,
  findUserMessageByClientOpId,
  getLastMessageRole,
  truncateMessagesAfter,
  shiftMessagePositions,
  countMessages,
  countUserMessages,
  findMessagePos,
  listMessageRowsPage,
  listMessageRowsFromPos,
  lastMessageTimestamp,
  listConversationIdsWithMessagesBetween,
  listMessages,
  listRecentMessages,
  listMessagesBeforePos,
  listMessagesByPosRange,
  listMessagesPage,
  getEarliestMessageDay,
  sumConversationUsage,
  sumConversationUsageBetween,
} from "./repos/message-repo.ts";
export { searchMessagesFts, countSearchableMessages } from "./repos/message-fts-repo.ts";
