/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as ParlorRouteRouteImport } from './routes/parlor/route'
import { Route as ChamberRouteRouteImport } from './routes/chamber/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopPathRouteImport } from './routes/workshop/$path'
import { Route as StudioShortVideoRouteImport } from './routes/studio/short-video'
import { Route as StudioPairProgrammingRouteImport } from './routes/studio/pair-programming'
import { Route as StudioNovelRouteImport } from './routes/studio/novel'
import { Route as ParlorSessionsRouteImport } from './routes/parlor/sessions'
import { Route as ParlorChatRouteImport } from './routes/parlor/chat'
import { Route as ChamberToolsRouteImport } from './routes/chamber/tools'
import { Route as ChamberSessionsRouteImport } from './routes/chamber/sessions'
import { Route as ChamberMemoryRouteImport } from './routes/chamber/memory'
import { Route as ChamberMcpRouteImport } from './routes/chamber/mcp'
import { Route as ChamberDashboardRouteImport } from './routes/chamber/dashboard'
import { Route as ChamberCronRouteImport } from './routes/chamber/cron'
import { Route as ChamberConfigRouteImport } from './routes/chamber/config'
import { Route as ChamberCommandsRouteImport } from './routes/chamber/commands'
import { Route as ChamberAcpRouteImport } from './routes/chamber/acp'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ParlorRouteRoute = ParlorRouteRouteImport.update({
  id: '/parlor',
  path: '/parlor',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamberRouteRoute = ChamberRouteRouteImport.update({
  id: '/chamber',
  path: '/chamber',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopPathRoute = WorkshopPathRouteImport.update({
  id: '/$path',
  path: '/$path',
  getParentRoute: () => WorkshopRoute,
} as any)
const StudioShortVideoRoute = StudioShortVideoRouteImport.update({
  id: '/short-video',
  path: '/short-video',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioPairProgrammingRoute = StudioPairProgrammingRouteImport.update({
  id: '/pair-programming',
  path: '/pair-programming',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioNovelRoute = StudioNovelRouteImport.update({
  id: '/novel',
  path: '/novel',
  getParentRoute: () => StudioRouteRoute,
} as any)
const ParlorSessionsRoute = ParlorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ParlorRouteRoute,
} as any)
const ParlorChatRoute = ParlorChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ParlorRouteRoute,
} as any)
const ChamberToolsRoute = ChamberToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => ChamberRouteRoute,
} as any)
const ChamberSessionsRoute = ChamberSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ChamberRouteRoute,
} as any)
const ChamberMemoryRoute = ChamberMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => ChamberRouteRoute,
} as any)
const ChamberMcpRoute = ChamberMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ChamberRouteRoute,
} as any)
const ChamberDashboardRoute = ChamberDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ChamberRouteRoute,
} as any)
const ChamberCronRoute = ChamberCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => ChamberRouteRoute,
} as any)
const ChamberConfigRoute = ChamberConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ChamberRouteRoute,
} as any)
const ChamberCommandsRoute = ChamberCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => ChamberRouteRoute,
} as any)
const ChamberAcpRoute = ChamberAcpRouteImport.update({
  id: '/acp',
  path: '/acp',
  getParentRoute: () => ChamberRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chamber': typeof ChamberRouteRouteWithChildren
  '/parlor': typeof ParlorRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/workshop': typeof WorkshopRouteWithChildren
  '/chamber/acp': typeof ChamberAcpRoute
  '/chamber/commands': typeof ChamberCommandsRoute
  '/chamber/config': typeof ChamberConfigRoute
  '/chamber/cron': typeof ChamberCronRoute
  '/chamber/dashboard': typeof ChamberDashboardRoute
  '/chamber/mcp': typeof ChamberMcpRoute
  '/chamber/memory': typeof ChamberMemoryRoute
  '/chamber/sessions': typeof ChamberSessionsRoute
  '/chamber/tools': typeof ChamberToolsRoute
  '/parlor/chat': typeof ParlorChatRoute
  '/parlor/sessions': typeof ParlorSessionsRoute
  '/studio/novel': typeof StudioNovelRoute
  '/studio/pair-programming': typeof StudioPairProgrammingRoute
  '/studio/short-video': typeof StudioShortVideoRoute
  '/workshop/$path': typeof WorkshopPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chamber': typeof ChamberRouteRouteWithChildren
  '/parlor': typeof ParlorRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/workshop': typeof WorkshopRouteWithChildren
  '/chamber/acp': typeof ChamberAcpRoute
  '/chamber/commands': typeof ChamberCommandsRoute
  '/chamber/config': typeof ChamberConfigRoute
  '/chamber/cron': typeof ChamberCronRoute
  '/chamber/dashboard': typeof ChamberDashboardRoute
  '/chamber/mcp': typeof ChamberMcpRoute
  '/chamber/memory': typeof ChamberMemoryRoute
  '/chamber/sessions': typeof ChamberSessionsRoute
  '/chamber/tools': typeof ChamberToolsRoute
  '/parlor/chat': typeof ParlorChatRoute
  '/parlor/sessions': typeof ParlorSessionsRoute
  '/studio/novel': typeof StudioNovelRoute
  '/studio/pair-programming': typeof StudioPairProgrammingRoute
  '/studio/short-video': typeof StudioShortVideoRoute
  '/workshop/$path': typeof WorkshopPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chamber': typeof ChamberRouteRouteWithChildren
  '/parlor': typeof ParlorRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/workshop': typeof WorkshopRouteWithChildren
  '/chamber/acp': typeof ChamberAcpRoute
  '/chamber/commands': typeof ChamberCommandsRoute
  '/chamber/config': typeof ChamberConfigRoute
  '/chamber/cron': typeof ChamberCronRoute
  '/chamber/dashboard': typeof ChamberDashboardRoute
  '/chamber/mcp': typeof ChamberMcpRoute
  '/chamber/memory': typeof ChamberMemoryRoute
  '/chamber/sessions': typeof ChamberSessionsRoute
  '/chamber/tools': typeof ChamberToolsRoute
  '/parlor/chat': typeof ParlorChatRoute
  '/parlor/sessions': typeof ParlorSessionsRoute
  '/studio/novel': typeof StudioNovelRoute
  '/studio/pair-programming': typeof StudioPairProgrammingRoute
  '/studio/short-video': typeof StudioShortVideoRoute
  '/workshop/$path': typeof WorkshopPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chamber'
    | '/parlor'
    | '/studio'
    | '/workshop'
    | '/chamber/acp'
    | '/chamber/commands'
    | '/chamber/config'
    | '/chamber/cron'
    | '/chamber/dashboard'
    | '/chamber/mcp'
    | '/chamber/memory'
    | '/chamber/sessions'
    | '/chamber/tools'
    | '/parlor/chat'
    | '/parlor/sessions'
    | '/studio/novel'
    | '/studio/pair-programming'
    | '/studio/short-video'
    | '/workshop/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chamber'
    | '/parlor'
    | '/studio'
    | '/workshop'
    | '/chamber/acp'
    | '/chamber/commands'
    | '/chamber/config'
    | '/chamber/cron'
    | '/chamber/dashboard'
    | '/chamber/mcp'
    | '/chamber/memory'
    | '/chamber/sessions'
    | '/chamber/tools'
    | '/parlor/chat'
    | '/parlor/sessions'
    | '/studio/novel'
    | '/studio/pair-programming'
    | '/studio/short-video'
    | '/workshop/$path'
  id:
    | '__root__'
    | '/'
    | '/chamber'
    | '/parlor'
    | '/studio'
    | '/workshop'
    | '/chamber/acp'
    | '/chamber/commands'
    | '/chamber/config'
    | '/chamber/cron'
    | '/chamber/dashboard'
    | '/chamber/mcp'
    | '/chamber/memory'
    | '/chamber/sessions'
    | '/chamber/tools'
    | '/parlor/chat'
    | '/parlor/sessions'
    | '/studio/novel'
    | '/studio/pair-programming'
    | '/studio/short-video'
    | '/workshop/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChamberRouteRoute: typeof ChamberRouteRouteWithChildren
  ParlorRouteRoute: typeof ParlorRouteRouteWithChildren
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  WorkshopRoute: typeof WorkshopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parlor': {
      id: '/parlor'
      path: '/parlor'
      fullPath: '/parlor'
      preLoaderRoute: typeof ParlorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamber': {
      id: '/chamber'
      path: '/chamber'
      fullPath: '/chamber'
      preLoaderRoute: typeof ChamberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop/$path': {
      id: '/workshop/$path'
      path: '/$path'
      fullPath: '/workshop/$path'
      preLoaderRoute: typeof WorkshopPathRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/studio/short-video': {
      id: '/studio/short-video'
      path: '/short-video'
      fullPath: '/studio/short-video'
      preLoaderRoute: typeof StudioShortVideoRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/pair-programming': {
      id: '/studio/pair-programming'
      path: '/pair-programming'
      fullPath: '/studio/pair-programming'
      preLoaderRoute: typeof StudioPairProgrammingRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/novel': {
      id: '/studio/novel'
      path: '/novel'
      fullPath: '/studio/novel'
      preLoaderRoute: typeof StudioNovelRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/parlor/sessions': {
      id: '/parlor/sessions'
      path: '/sessions'
      fullPath: '/parlor/sessions'
      preLoaderRoute: typeof ParlorSessionsRouteImport
      parentRoute: typeof ParlorRouteRoute
    }
    '/parlor/chat': {
      id: '/parlor/chat'
      path: '/chat'
      fullPath: '/parlor/chat'
      preLoaderRoute: typeof ParlorChatRouteImport
      parentRoute: typeof ParlorRouteRoute
    }
    '/chamber/tools': {
      id: '/chamber/tools'
      path: '/tools'
      fullPath: '/chamber/tools'
      preLoaderRoute: typeof ChamberToolsRouteImport
      parentRoute: typeof ChamberRouteRoute
    }
    '/chamber/sessions': {
      id: '/chamber/sessions'
      path: '/sessions'
      fullPath: '/chamber/sessions'
      preLoaderRoute: typeof ChamberSessionsRouteImport
      parentRoute: typeof ChamberRouteRoute
    }
    '/chamber/memory': {
      id: '/chamber/memory'
      path: '/memory'
      fullPath: '/chamber/memory'
      preLoaderRoute: typeof ChamberMemoryRouteImport
      parentRoute: typeof ChamberRouteRoute
    }
    '/chamber/mcp': {
      id: '/chamber/mcp'
      path: '/mcp'
      fullPath: '/chamber/mcp'
      preLoaderRoute: typeof ChamberMcpRouteImport
      parentRoute: typeof ChamberRouteRoute
    }
    '/chamber/dashboard': {
      id: '/chamber/dashboard'
      path: '/dashboard'
      fullPath: '/chamber/dashboard'
      preLoaderRoute: typeof ChamberDashboardRouteImport
      parentRoute: typeof ChamberRouteRoute
    }
    '/chamber/cron': {
      id: '/chamber/cron'
      path: '/cron'
      fullPath: '/chamber/cron'
      preLoaderRoute: typeof ChamberCronRouteImport
      parentRoute: typeof ChamberRouteRoute
    }
    '/chamber/config': {
      id: '/chamber/config'
      path: '/config'
      fullPath: '/chamber/config'
      preLoaderRoute: typeof ChamberConfigRouteImport
      parentRoute: typeof ChamberRouteRoute
    }
    '/chamber/commands': {
      id: '/chamber/commands'
      path: '/commands'
      fullPath: '/chamber/commands'
      preLoaderRoute: typeof ChamberCommandsRouteImport
      parentRoute: typeof ChamberRouteRoute
    }
    '/chamber/acp': {
      id: '/chamber/acp'
      path: '/acp'
      fullPath: '/chamber/acp'
      preLoaderRoute: typeof ChamberAcpRouteImport
      parentRoute: typeof ChamberRouteRoute
    }
  }
}

interface ChamberRouteRouteChildren {
  ChamberAcpRoute: typeof ChamberAcpRoute
  ChamberCommandsRoute: typeof ChamberCommandsRoute
  ChamberConfigRoute: typeof ChamberConfigRoute
  ChamberCronRoute: typeof ChamberCronRoute
  ChamberDashboardRoute: typeof ChamberDashboardRoute
  ChamberMcpRoute: typeof ChamberMcpRoute
  ChamberMemoryRoute: typeof ChamberMemoryRoute
  ChamberSessionsRoute: typeof ChamberSessionsRoute
  ChamberToolsRoute: typeof ChamberToolsRoute
}

const ChamberRouteRouteChildren: ChamberRouteRouteChildren = {
  ChamberAcpRoute: ChamberAcpRoute,
  ChamberCommandsRoute: ChamberCommandsRoute,
  ChamberConfigRoute: ChamberConfigRoute,
  ChamberCronRoute: ChamberCronRoute,
  ChamberDashboardRoute: ChamberDashboardRoute,
  ChamberMcpRoute: ChamberMcpRoute,
  ChamberMemoryRoute: ChamberMemoryRoute,
  ChamberSessionsRoute: ChamberSessionsRoute,
  ChamberToolsRoute: ChamberToolsRoute,
}

const ChamberRouteRouteWithChildren = ChamberRouteRoute._addFileChildren(
  ChamberRouteRouteChildren,
)

interface ParlorRouteRouteChildren {
  ParlorChatRoute: typeof ParlorChatRoute
  ParlorSessionsRoute: typeof ParlorSessionsRoute
}

const ParlorRouteRouteChildren: ParlorRouteRouteChildren = {
  ParlorChatRoute: ParlorChatRoute,
  ParlorSessionsRoute: ParlorSessionsRoute,
}

const ParlorRouteRouteWithChildren = ParlorRouteRoute._addFileChildren(
  ParlorRouteRouteChildren,
)

interface StudioRouteRouteChildren {
  StudioNovelRoute: typeof StudioNovelRoute
  StudioPairProgrammingRoute: typeof StudioPairProgrammingRoute
  StudioShortVideoRoute: typeof StudioShortVideoRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioNovelRoute: StudioNovelRoute,
  StudioPairProgrammingRoute: StudioPairProgrammingRoute,
  StudioShortVideoRoute: StudioShortVideoRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

interface WorkshopRouteChildren {
  WorkshopPathRoute: typeof WorkshopPathRoute
}

const WorkshopRouteChildren: WorkshopRouteChildren = {
  WorkshopPathRoute: WorkshopPathRoute,
}

const WorkshopRouteWithChildren = WorkshopRoute._addFileChildren(
  WorkshopRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChamberRouteRoute: ChamberRouteRouteWithChildren,
  ParlorRouteRoute: ParlorRouteRouteWithChildren,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  WorkshopRoute: WorkshopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
