/** GENERATED by scripts/gen-shared-shapes — do not edit by hand. */
import { z } from "zod";
import { platformInfoSchema } from "../jsonb/platform-info.ts";
import { conversationModuleSchema } from "../entity/enums.ts";
import { compressionJsonSchema } from "../jsonb/compression.ts";
import { temporalDayJsonSchema } from "../jsonb/temporal-day.ts";
import {
  acpTasksSchema,
  awaitingClarifySchema,
  conversationCachedToolsetsSchema,
  conversationFunctionsSchema,
  conversationGoalSchema,
  conversationStagedToolsetsSchema,
  conversationTodoStoreSchema,
} from "../jsonb/conversation-meta-jsonb.ts";

export const conversationSelectSchema = z.object({
  id: z.string(),
  model: z.string(),
  title: z.string().nullable(),
  cwd: z.string().nullable(),
  system_prompt: z.string().nullable(),
  /** CST 02:00 日界刷新用：上次全量构建 system_prompt 的时刻 */
  system_prompt_built_at: z.coerce.date().nullable().optional(),
  platform_info: platformInfoSchema.nullable(),
  /** Prompt 模式模块（与 platform_info 通道身份正交）。chat = 数字人类；coding = 工作模式；NULL = 数字人类（兼容旧行）。 */
  module: conversationModuleSchema.nullable().optional(),
  compression: compressionJsonSchema.nullable(),
  /** 当天对话级时间摘要 chunks（操作态，不可引用） */
  temporal_day: temporalDayJsonSchema.nullable(),
  todos: conversationTodoStoreSchema,
  awaiting_clarify: awaitingClarifySchema.nullable(),
  acp_tasks: acpTasksSchema.nullable(),
  goal: conversationGoalSchema.nullable(),
  cached_toolsets: conversationCachedToolsetsSchema,
  staged_toolsets: conversationStagedToolsetsSchema,
  functions: conversationFunctionsSchema,
  debug: z.boolean(),
  archived_at: z.coerce.date().nullable().optional(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
});

export const conversationInsertSchema = z.object({
  id: z.string(),
  model: z.string(),
  title: z.string().nullable().optional(),
  cwd: z.string().nullable().optional(),
  system_prompt: z.string().nullable().optional(),
  /** CST 02:00 日界刷新用：上次全量构建 system_prompt 的时刻 */
  system_prompt_built_at: z.coerce.date().nullable().optional(),
  platform_info: platformInfoSchema.nullable(),
  /** Prompt 模式模块（与 platform_info 通道身份正交）。chat = 数字人类；coding = 工作模式；NULL = 数字人类（兼容旧行）。 */
  module: conversationModuleSchema.nullable().optional(),
  compression: compressionJsonSchema.nullable(),
  /** 当天对话级时间摘要 chunks（操作态，不可引用） */
  temporal_day: temporalDayJsonSchema.nullable(),
  todos: conversationTodoStoreSchema,
  awaiting_clarify: awaitingClarifySchema.nullable(),
  acp_tasks: acpTasksSchema.nullable(),
  goal: conversationGoalSchema.nullable(),
  cached_toolsets: conversationCachedToolsetsSchema,
  staged_toolsets: conversationStagedToolsetsSchema,
  functions: conversationFunctionsSchema,
  debug: z.boolean().optional(),
  archived_at: z.coerce.date().nullable().optional(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
});

export type ConversationSelect = z.infer<typeof conversationSelectSchema>;
export type ConversationInsert = z.infer<typeof conversationInsertSchema>;
