/**
 * 构建期替代 createSelectSchema / createInsertSchema：
 * 读 pgTable 列元数据 + 覆盖映射 → emit 无 drizzle 的纯 Zod 到 shared/pg-shapes/rows。
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { getTableColumns, type Column, type Table } from "drizzle-orm";

import { TABLE_SPECS, type ColumnOverride, type TableGenSpec } from "./config.ts";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "../..");
const OUT_DIR = join(REPO_ROOT, "packages/shared/pg-shapes/rows");

const GENERATED_BANNER = `/** GENERATED by scripts/gen-shared-shapes — do not edit by hand. */\n`;

type ColMeta = Column & {
  primary?: boolean;
  dataType: string;
  columnType: string;
  notNull: boolean;
  hasDefault: boolean;
  generated?: unknown;
  generatedIdentity?: unknown;
};

function isGeneratedAlways(col: ColMeta): boolean {
  const g = col.generated as { type?: string } | undefined;
  if (g?.type === "always") return true;
  if (col.generatedIdentity) return true;
  return false;
}

function baseZodExpr(col: ColMeta): string {
  const { dataType, columnType } = col;
  if (columnType === "PgCustomColumn" || dataType === "custom") {
    // pgTimestamptz 等：存储侧 Date（coerce 兼容驱动字符串）
    return "z.coerce.date()";
  }
  if (columnType === "PgJsonb") {
    return "z.unknown()";
  }
  if (columnType === "PgBoolean" || dataType === "boolean") {
    return "z.boolean()";
  }
  if (
    columnType === "PgInteger" ||
    columnType === "PgSmallInt" ||
    columnType === "PgBigInt53" ||
    dataType === "number" ||
    dataType.startsWith("number")
  ) {
    return "z.number()";
  }
  if (columnType === "PgText" || columnType === "PgVarchar" || dataType === "string") {
    return "z.string()";
  }
  return "z.unknown()";
}

/**
 * 对齐 drizzle-orm/zod：
 * - Select：nullable=!notNull；optional 永不；无对象 override 时套 wrapper
 * - Insert：nullable=!notNull；optional=!notNull || (notNull&&hasDefault)；generated → 跳过
 * - 对象 override：直接用 expr，不再自动套 nullable/optional
 */
function fieldExpr(
  col: ColMeta,
  mode: "select" | "insert",
  override: ColumnOverride | undefined,
): string | null {
  if (mode === "insert" && isGeneratedAlways(col)) return null;

  if (override) {
    return override.expr;
  }

  let expr = baseZodExpr(col);
  const nullable = !col.notNull;
  if (nullable) expr = `${expr}.nullable()`;

  if (mode === "insert") {
    const optional = !col.notNull || (col.notNull && col.hasDefault);
    if (optional) expr = `${expr}.optional()`;
  }

  return expr;
}

function mergeImports(
  overrides: Record<string, ColumnOverride> | undefined,
): Array<{ from: string; names: string[] }> {
  const map = new Map<string, Set<string>>();
  for (const ov of Object.values(overrides ?? {})) {
    for (const imp of ov.imports) {
      let set = map.get(imp.from);
      if (!set) {
        set = new Set();
        map.set(imp.from, set);
      }
      for (const n of imp.names) set.add(n);
    }
  }
  return [...map.entries()].map(([from, names]) => ({
    from,
    names: [...names].toSorted(),
  }));
}

function emitObjectFields(
  cols: Record<string, ColMeta>,
  mode: "select" | "insert",
  spec: TableGenSpec,
): string {
  const lines: string[] = [];
  for (const [name, col] of Object.entries(cols)) {
    const expr = fieldExpr(col, mode, spec.overrides?.[name]);
    if (expr == null) continue;
    const comment = spec.comments?.[name];
    if (comment) {
      lines.push(`  /** ${comment} */`);
    }
    lines.push(`  ${name}: ${expr},`);
  }
  return lines.join("\n");
}

async function loadTable(spec: TableGenSpec): Promise<Table> {
  const modPath = join(REPO_ROOT, spec.tableModule);
  const imported: unknown = await import(pathToFileURL(modPath).href);
  if (imported == null || typeof imported !== "object") {
    throw new Error(`Invalid module ${spec.tableModule}`);
  }
  const table: unknown = (imported as Record<string, unknown>)[spec.tableExport];
  if (table == null || typeof table !== "object") {
    throw new Error(`Missing export ${spec.tableExport} from ${spec.tableModule}`);
  }
  return table as Table;
}

async function generateTable(spec: TableGenSpec): Promise<string> {
  const table = await loadTable(spec);
  const cols = getTableColumns(table) as Record<string, ColMeta>;

  const imports = mergeImports(spec.overrides);
  const importLines = [
    'import { z } from "zod";',
    ...imports.map((imp) => {
      if (imp.names.length <= 3) {
        return `import { ${imp.names.join(", ")} } from "${imp.from}";`;
      }
      const body = imp.names.map((n) => `  ${n},`).join("\n");
      return `import {\n${body}\n} from "${imp.from}";`;
    }),
  ];

  const selectName = `${spec.exportPrefix}SelectSchema`;
  const insertName = `${spec.exportPrefix}InsertSchema`;
  const selectType = `${capitalize(spec.exportPrefix)}Select`;
  const insertType = `${capitalize(spec.exportPrefix)}Insert`;

  const selectTypeName = selectType;
  const insertTypeName = insertType;

  return `${GENERATED_BANNER}${importLines.join("\n")}

export const ${selectName} = z.object({
${emitObjectFields(cols, "select", spec)}
});

export const ${insertName} = z.object({
${emitObjectFields(cols, "insert", spec)}
});

export type ${selectTypeName} = z.infer<typeof ${selectName}>;
export type ${insertTypeName} = z.infer<typeof ${insertName}>;
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function emitRowsIndex(files: string[]): string {
  const exports = files
    .map((f) => `export * from "./${f}.ts";`)
    .concat(['export * from "./memory-rows.ts";', 'export * from "./entity-row.ts";'])
    .join("\n");
  return `${GENERATED_BANNER}${exports}\n`;
}

async function main(): Promise<void> {
  mkdirSync(OUT_DIR, { recursive: true });
  const generatedBases: string[] = [];

  for (const spec of TABLE_SPECS) {
    const body = await generateTable(spec);
    const outPath = join(OUT_DIR, `${spec.fileBase}.gen.ts`);
    writeFileSync(outPath, body, "utf8");
    generatedBases.push(`${spec.fileBase}.gen`);
    console.log(`wrote ${outPath}`);
  }

  writeFileSync(join(OUT_DIR, "index.ts"), emitRowsIndex(generatedBases), "utf8");
  console.log("ok");
}

await main();
