export const POMODORO_FLOAT_PORT_START = 4196;
export const POMODORO_FLOAT_WINDOW_WIDTH = 220;
export const POMODORO_FLOAT_WINDOW_HEIGHT = 156;
export const POMODORO_FLOAT_PICKER_WIDTH = 320;
export const POMODORO_FLOAT_PICKER_HEIGHT = 420;
