export type { StoredMessage as Message } from "@freeanima/habitat/core/db/domain";
export { isConversationMeta } from "@freeanima/habitat/core/db/domain";

export {
  allocateConversationCwd,
  loadConversationTools,
  loadConversationMeta,
  generateConversationId,
  countConversationsByPlatform,
  listConversationSummaries,
  listConversationSummariesPage,
  listConversations,
  conversationExists,
  load,
  loadMessagePage,
  loadMessagesBeforePos,
  countMessages,
  countUserMessages,
  loadForRuntime,
  appendMessage,
  appendConversationMeta,
  initConversation,
  newConversation,
  findConversationByOrigin,
  activateConversationOrigin,
  updateConversationMetaField,
  patchConversationOrigin,
  rebuildConversationSystemPrompt,
  rebuildConversationCache,
  ensureSystemPromptFresh,
  refreshSystemPromptOnResume,
  assertConversationPlatform,
  appendUserTurn,
  getMaxMessagePos,
  findUserMessageByClientOpId,
  getLastMessageRole,
  updateConversationMeta,
  setConversationTitle,
  archiveConversation,
  unarchiveConversation,
  pinConversation,
  unpinConversation,
  deleteUserConversation,
  getConversationTitle,
  getConversationCwd,
  setConversationCwd,
  rollbackToLastUser,
  rollbackBeforeLastUser,
  cleanupDebugConversations,
  cleanupStaleConversations,
  STALE_SESSION_MIN_AGE_MS,
} from "./conversation-crud.ts";
