import type { SessionStorePort } from "@freeanima/core/repos";
import * as messageFtsRepo from "./repos/message-fts-repo.ts";
import * as messageRepo from "./repos/message-repo.ts";
import * as sessionRepo from "./repos/session-repo.ts";

/** PostgreSQL SessionStorePort implementation */
export const pgSessionStore = {
  getSessionMeta: sessionRepo.getSessionMeta,
  upsertSessionMeta: sessionRepo.upsertSessionMeta,
  patchSessionMeta: sessionRepo.patchSessionMeta,
  updateCompression: sessionRepo.updateCompression,
  updateTodos: sessionRepo.updateTodos,
  appendMessage: messageRepo.appendMessage,
  appendMessageReturningId: messageRepo.appendMessageReturningId,
  getMessageContentById: messageRepo.getMessageContentById,
  updateMessageContent: messageRepo.updateMessageContent,
  nextMessagePos: messageRepo.nextMessagePos,
  truncateMessagesAfter: messageRepo.truncateMessagesAfter,
  shiftMessagePositions: messageRepo.shiftMessagePositions,
  sessionExists: sessionRepo.sessionExists,
  deleteSession: sessionRepo.deleteSession,
  listSessionIds: sessionRepo.listSessionIds,
  listDebugSessionIds: sessionRepo.listDebugSessionIds,
  listSessionSummaries: sessionRepo.listSessionSummaries,
  countSessionsByPlatform: sessionRepo.countSessionsByPlatform,
  deleteDebugSessions: sessionRepo.deleteDebugSessions,
  findSessionIdByPlatformInfo: sessionRepo.findSessionIdByPlatformInfo,
  listSessionIdsMatchingPlatformProbe: sessionRepo.listSessionIdsMatchingPlatformProbe,
  countMessages: messageRepo.countMessages,
  countUserMessages: messageRepo.countUserMessages,
  findMessagePos: messageRepo.findMessagePos,
  listMessageRowsPage: messageRepo.listMessageRowsPage,
  listMessageRowsFromPos: messageRepo.listMessageRowsFromPos,
  lastMessageTimestamp: messageRepo.lastMessageTimestamp,
  searchMessagesFts: messageFtsRepo.searchMessagesFts,
  countSearchableMessages: messageFtsRepo.countSearchableMessages,
  getSessionMetaLite: sessionRepo.getSessionMetaLite,
  getSessionTools: sessionRepo.getSessionTools,
  listMessages: messageRepo.listMessages,
  listMessagesByPosRange: messageRepo.listMessagesByPosRange,
  listMessagesPage: messageRepo.listMessagesPage,
  listSessionIdsUpdatedBetween: sessionRepo.listSessionIdsUpdatedBetween,
  getEarliestSessionDay: sessionRepo.getEarliestSessionDay,
  listStaleSessionIdsForCleanup: sessionRepo.listStaleSessionIdsForCleanup,
  deleteStaleSessions: sessionRepo.deleteStaleSessions,
} satisfies SessionStorePort;
