import {
  tasklistCreateInputSchema,
  tasklistCreateOutputSchema,
  tasklistDeleteInputSchema,
  tasklistDeleteOutputSchema,
  tasklistListInputSchema,
  tasklistListOutputSchema,
  tasklistStatsInputSchema,
  tasklistStatsOutputSchema,
  tasklistPatchInputSchema,
  tasklistPatchOutputSchema,
  tasklistItemListInputSchema,
  tasklistItemListOutputSchema,
  tasklistItemCreateInputSchema,
  tasklistItemCreateOutputSchema,
  projectItemListInputSchema,
  projectItemListOutputSchema,
  projectItemCreateInputSchema,
  projectItemCreateOutputSchema,
  smartlistListInputSchema,
  smartlistListOutputSchema,
  smartlistStatsInputSchema,
  smartlistStatsOutputSchema,
  smartlistCreateInputSchema,
  smartlistCreateOutputSchema,
  smartlistPatchInputSchema,
  smartlistPatchOutputSchema,
  smartlistDeleteInputSchema,
  smartlistDeleteOutputSchema,
  taskCompleteInputSchema,
  taskCompleteOutputSchema,
  taskCompleteForeverInputSchema,
  taskCompleteForeverOutputSchema,
  taskDeleteInputSchema,
  taskDeleteOutputSchema,
  taskListOccurrencesInputSchema,
  taskListOccurrencesOutputSchema,
  taskMoveToListInputSchema,
  taskMoveToListOutputSchema,
  taskMoveToProjectInputSchema,
  taskMoveToProjectOutputSchema,
  taskPatchInputSchema,
  taskPatchOutputSchema,
  taskSearchInputSchema,
  taskSearchOutputSchema,
  taskSkipInputSchema,
  taskSkipOutputSchema,
  taskUncompleteInputSchema,
  taskUncompleteOutputSchema,
} from "@freeanima/shared/rpc-contract/frames/task";

import { defineHabitatMethod, dualTransportMeta } from "@freeanima/shared/habitat-contract";

export const taskMethodDefs = {
  "tasklist.list": defineHabitatMethod({
    input: tasklistListInputSchema,
    output: tasklistListOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "tasklist.stats": defineHabitatMethod({
    input: tasklistStatsInputSchema,
    output: tasklistStatsOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "tasklist.create": defineHabitatMethod({
    input: tasklistCreateInputSchema,
    output: tasklistCreateOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "tasklist.patch": defineHabitatMethod({
    input: tasklistPatchInputSchema,
    output: tasklistPatchOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "tasklist.delete": defineHabitatMethod({
    input: tasklistDeleteInputSchema,
    output: tasklistDeleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "tasklist.item.list": defineHabitatMethod({
    input: tasklistItemListInputSchema,
    output: tasklistItemListOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "tasklist.item.create": defineHabitatMethod({
    input: tasklistItemCreateInputSchema,
    output: tasklistItemCreateOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "smartlist.list": defineHabitatMethod({
    input: smartlistListInputSchema,
    output: smartlistListOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "smartlist.stats": defineHabitatMethod({
    input: smartlistStatsInputSchema,
    output: smartlistStatsOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "smartlist.create": defineHabitatMethod({
    input: smartlistCreateInputSchema,
    output: smartlistCreateOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "smartlist.patch": defineHabitatMethod({
    input: smartlistPatchInputSchema,
    output: smartlistPatchOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "smartlist.delete": defineHabitatMethod({
    input: smartlistDeleteInputSchema,
    output: smartlistDeleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "project.item.list": defineHabitatMethod({
    input: projectItemListInputSchema,
    output: projectItemListOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "project.item.create": defineHabitatMethod({
    input: projectItemCreateInputSchema,
    output: projectItemCreateOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.patch": defineHabitatMethod({
    input: taskPatchInputSchema,
    output: taskPatchOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.moveToProject": defineHabitatMethod({
    input: taskMoveToProjectInputSchema,
    output: taskMoveToProjectOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.moveToList": defineHabitatMethod({
    input: taskMoveToListInputSchema,
    output: taskMoveToListOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.complete": defineHabitatMethod({
    input: taskCompleteInputSchema,
    output: taskCompleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.skip": defineHabitatMethod({
    input: taskSkipInputSchema,
    output: taskSkipOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.completeForever": defineHabitatMethod({
    input: taskCompleteForeverInputSchema,
    output: taskCompleteForeverOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.listOccurrences": defineHabitatMethod({
    input: taskListOccurrencesInputSchema,
    output: taskListOccurrencesOutputSchema,
    meta: dualTransportMeta(true),
  }),
  "task.uncomplete": defineHabitatMethod({
    input: taskUncompleteInputSchema,
    output: taskUncompleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.delete": defineHabitatMethod({
    input: taskDeleteInputSchema,
    output: taskDeleteOutputSchema,
    meta: dualTransportMeta(false),
  }),
  "task.search": defineHabitatMethod({
    input: taskSearchInputSchema,
    output: taskSearchOutputSchema,
    meta: dualTransportMeta(true),
  }),
} as const;
