import {
  PATHS,
  TUNNEL_CREDENTIAL_REFS,
  type TunnelConfig,
  type TunnelConfigFields,
} from "@freeanima/core/config";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  createTunnel,
  ensureTunnelCnameRecord,
  findZoneForHostname,
  getTunnelToken,
  listAccounts,
  listZones,
  putTunnelConfig,
  verifyApiToken,
} from "./cloudflare-api.ts";
import {
  createAccessApplication,
  createEmailAllowPolicy,
  manualAccessDashboardSteps,
} from "./access-api.ts";
import { resolveTunnelApiToken } from "./resolve-credential.ts";

export type SetupWizardInput = {
  hostname: string;
  teamName: string;
  email: string;
  hubPort: number;
  sessionDuration: string;
  apiToken?: string;
  createAccessViaApi: boolean;
  accountId?: string;
  /** 写入 pass 与更新 config.yaml */
  saveApiToken: (token: string) => void;
  saveTunnelCredentials: (json: string) => void;
  /** 每步合并写入 config.yaml */
  patchConfig: (patch: Partial<TunnelConfigFields>) => void;
  onProgress: (message: string) => void;
};

export type SetupWizardResult = {
  tunnel: TunnelConfig;
  publicUrl: string;
  manualAccessSteps: string[] | null;
  dnsConfigured: boolean;
  manualDnsSteps: string[] | null;
};

function renderCloudflaredConfig(
  hostname: string,
  hubPort: number,
  credentialsFile: string,
  tunnelId?: string,
): string {
  const tunnelLine = tunnelId ? `tunnel: ${tunnelId}\n` : "";
  return `# Generated by anima tunnel setup
${tunnelLine}credentials-file: ${credentialsFile}
ingress:
  - hostname: ${hostname}
    service: http://127.0.0.1:${hubPort}
  - service: http_status:404
`;
}

export function writeCloudflaredConfig(
  hostname: string,
  hubPort: number,
  credentialsFile: string,
  tunnelId?: string,
): string {
  mkdirSync(PATHS.cloudflaredConfigDir, { recursive: true });
  const content = renderCloudflaredConfig(hostname, hubPort, credentialsFile, tunnelId);
  writeFileSync(PATHS.cloudflaredConfigFile, content, "utf-8");
  return PATHS.cloudflaredConfigFile;
}

export async function runSetupWizard(input: SetupWizardInput): Promise<SetupWizardResult> {
  const tunnelName = `freeanima-${input.hostname.replace(/\./g, "-")}`;
  let accountId = input.accountId;
  let tunnelId = "";
  let zoneId: string | undefined;
  let audience: string | undefined;
  let manualAccessSteps: string[] | null = null;
  let manualDnsSteps: string[] | null = null;
  let dnsConfigured = false;

  const credentialsFile = join(PATHS.cloudflaredConfigDir, "credentials.json");

  if (input.apiToken) {
    const apiToken = resolveTunnelApiToken(input.apiToken);
    input.onProgress("验证 Cloudflare API Token…");
    await verifyApiToken(apiToken);
    input.saveApiToken(apiToken);
    input.patchConfig({
      credentials: { api_token: TUNNEL_CREDENTIAL_REFS.apiToken },
    });

    if (!accountId) {
      input.onProgress("获取 Cloudflare 账号…");
      const accounts = await listAccounts(apiToken);
      if (accounts.length === 0) throw new Error("未找到 Cloudflare 账号");
      accountId = accounts[0]!.id;
      input.patchConfig({
        cloudflare: { account_id: accountId, tunnel_name: tunnelName },
      });
    }

    const apiOpts = { apiToken, accountId };

    input.onProgress("创建 Tunnel…");
    const tunnel = await createTunnel(apiOpts, tunnelName);
    tunnelId = tunnel.id;
    input.patchConfig({
      hostname: input.hostname,
      team_name: input.teamName,
      cloudflare: { account_id: accountId, tunnel_id: tunnelId, tunnel_name: tunnelName },
      access: {
        enabled: true,
        allowed_emails: [input.email],
        session_duration: input.sessionDuration,
      },
    });

    input.onProgress("获取 Tunnel 凭证…");
    const token = await getTunnelToken(apiOpts, tunnelId);
    input.saveTunnelCredentials(token);
    input.patchConfig({
      credentials: { tunnel_credentials: TUNNEL_CREDENTIAL_REFS.tunnelCredentials },
    });
    mkdirSync(PATHS.cloudflaredConfigDir, { recursive: true });
    writeFileSync(credentialsFile, token, "utf-8");

    input.onProgress("配置 Tunnel ingress…");
    await putTunnelConfig(apiOpts, tunnelId, {
      ingress: [
        { hostname: input.hostname, service: `http://127.0.0.1:${input.hubPort}` },
        { service: "http_status:404" },
      ],
    });

    input.onProgress("查找 DNS Zone…");
    const zones = await listZones(apiToken);
    const zone = findZoneForHostname(zones, input.hostname);
    if (zone) {
      zoneId = zone.id;
      input.patchConfig({ cloudflare: { zone_id: zoneId } });
      input.onProgress(`配置 DNS CNAME (${input.hostname})…`);
      const dns = await ensureTunnelCnameRecord(
        apiOpts,
        zone.id,
        zone.name,
        input.hostname,
        tunnelId,
      );
      if (dns.ok) {
        dnsConfigured = true;
        input.onProgress(dns.created ? "DNS CNAME 已创建" : "DNS CNAME 已存在");
      } else {
        manualDnsSteps = dns.manualSteps;
        input.onProgress(`DNS 未自动配置: ${dns.reason.split("\n")[0]}`);
      }
    } else {
      manualDnsSteps = [
        `未在 Cloudflare 账号中找到 ${input.hostname} 的 Zone`,
        "请确认域名已接入 Cloudflare，或在 Dashboard 手动添加 CNAME",
      ];
      input.onProgress("未找到匹配 Zone — 请手动创建 CNAME 指向 Tunnel");
    }

    if (input.createAccessViaApi) {
      input.onProgress("创建 Access Application…");
      const app = await createAccessApplication(apiOpts, {
        hostname: input.hostname,
        sessionDuration: input.sessionDuration,
      });
      audience = app.aud;
      input.patchConfig({ access: { audience } });
      input.onProgress("创建 Allow Policy…");
      await createEmailAllowPolicy(apiOpts, app.id, input.email);
    } else {
      manualAccessSteps = manualAccessDashboardSteps({
        hostname: input.hostname,
        teamName: input.teamName,
        email: input.email,
      });
    }
  } else {
    manualAccessSteps = manualAccessDashboardSteps({
      hostname: input.hostname,
      teamName: input.teamName,
      email: input.email,
    });
    input.patchConfig({
      hostname: input.hostname,
      team_name: input.teamName,
      access: {
        enabled: true,
        allowed_emails: [input.email],
        session_duration: input.sessionDuration,
      },
    });
    input.onProgress("无 API Token — 请按 Dashboard 步骤手动创建 Tunnel 与 Access");
  }

  writeCloudflaredConfig(input.hostname, input.hubPort, credentialsFile, tunnelId || undefined);

  const tunnelConfig: TunnelConfig = {
    enabled: true,
    hostname: input.hostname,
    team_name: input.teamName,
    access: {
      enabled: true,
      allowed_emails: [input.email],
      audience,
      session_duration: input.sessionDuration,
    },
    cloudflare: {
      account_id: accountId,
      tunnel_id: tunnelId || undefined,
      tunnel_name: tunnelName,
      zone_id: zoneId,
    },
    credentials: {
      api_token: input.apiToken ? TUNNEL_CREDENTIAL_REFS.apiToken : undefined,
      tunnel_credentials: tunnelId ? TUNNEL_CREDENTIAL_REFS.tunnelCredentials : undefined,
    },
  };

  input.patchConfig(tunnelConfig);

  return {
    tunnel: tunnelConfig,
    publicUrl: `https://${input.hostname}`,
    manualAccessSteps,
    dnsConfigured,
    manualDnsSteps,
  };
}

export { renderCloudflaredConfig, manualAccessDashboardSteps };
