#!/usr/bin/env bun
/**
 * 从 messages/en.json 生成 Paraglide 消息类型（供 noUncheckedIndexedAccess 下 m.*() 可调用）。
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import en from "../messages/en.json" with { type: "json" };

const repoRoot = join(import.meta.dirname, "..");
const outPath = join(repoRoot, "types/paraglide-messages.generated.d.ts");

const keys = Object.keys(en)
  .filter((k) => k !== "$schema")
  .toSorted();

const lines = keys.map((key) => `  readonly ${key}: ParaglideMessageFn;`);

const moduleExportLines = keys.map((key) => `  export const ${key}: ParaglideMessageFn;`);

const content = `// Generated by scripts/gen-paraglide-message-types.ts — do not edit.
type ParaglideMessageFn = (
  inputs?: Record<string, unknown>,
  options?: { locale?: "en" | "zh-cn" },
) => string;

type ParaglideMessageExports = {
${lines.join("\n")}
};

declare module "@paraglide/messages" {
  export const m: ParaglideMessageExports;
}

declare module "*/messages/paraglide/messages.js" {
  export const m: ParaglideMessageExports;
${moduleExportLines.join("\n")}
}
`;

writeFileSync(outPath, content);
console.log(`gen-paraglide-message-types: wrote ${keys.length} keys → ${outPath}`);
