#!/usr/bin/env bun
/**
 * 生成 bun --compile 入口：
 * - `with { type: "file" }` 嵌入全部 migration.sql
 * - `with { type: "file" }` 嵌入整个 Web dist（需已 build）
 * 再导入真实 CLI。由 build-cli-executable 调用。
 *
 * 用法：
 *   bun scripts/gen-standalone-compile-entry.ts --out path/to/entry.ts
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { Glob } from "bun";

const ROOT = join(import.meta.dir, "..");
const MIGRATIONS_DIR = join(ROOT, "src/core/migrations");
const WEB_DIST_DIR = join(ROOT, "src/app/shell/web/dist");
const CLI_ENTRY = join(ROOT, "src/app/cli/cli.ts");
const MIGRATIONS_REGISTER_MOD = join(ROOT, "src/core/db/migrations-embedded.ts");
const WEB_DIST_REGISTER_MOD = join(ROOT, "src/app/cli/web/web-dist-embedded.ts");

function parseOutPath(argv: string[]): string {
  const i = argv.indexOf("--out");
  const out = i >= 0 ? argv[i + 1] : undefined;
  if (!out?.trim()) {
    throw new Error("gen-standalone-compile-entry: missing --out <path>");
  }
  return out.trim();
}

function listMigrationNames(): string[] {
  return readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((name) => existsSync(join(MIGRATIONS_DIR, name, "migration.sql")))
    .toSorted((a, b) => a.localeCompare(b));
}

function listWebDistRels(): string[] {
  if (!existsSync(join(WEB_DIST_DIR, "index.html"))) {
    throw new Error(
      `gen-standalone-compile-entry: Web dist 缺失（${WEB_DIST_DIR}）。请先 bun run build:web`,
    );
  }
  const rels: string[] = [];
  for (const rel of new Glob("**/*").scanSync({ cwd: WEB_DIST_DIR, onlyFiles: true })) {
    const normalized = rel.split("\\").join("/");
    if (normalized === ".ok" || normalized.endsWith("/.ok")) continue;
    rels.push(normalized);
  }
  if (rels.length === 0) {
    throw new Error(`gen-standalone-compile-entry: Web dist 为空: ${WEB_DIST_DIR}`);
  }
  return rels.toSorted((a, b) => a.localeCompare(b));
}

function toImportPath(fromFile: string, targetFile: string): string {
  let rel = relative(dirname(fromFile), targetFile);
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel.split("\\").join("/");
}

function main(): void {
  const outPath = parseOutPath(process.argv.slice(2));
  const migrationNames = listMigrationNames();
  if (migrationNames.length === 0) {
    throw new Error(`gen-standalone-compile-entry: no migration.sql under ${MIGRATIONS_DIR}`);
  }
  const webRels = listWebDistRels();

  mkdirSync(dirname(outPath), { recursive: true });

  const migRegisterImport = toImportPath(outPath, MIGRATIONS_REGISTER_MOD);
  const webRegisterImport = toImportPath(outPath, WEB_DIST_REGISTER_MOD);
  const cliImport = toImportPath(outPath, CLI_ENTRY);

  const importLines: string[] = [];
  const migEntries: string[] = [];
  const webEntries: string[] = [];

  for (const [i, name] of migrationNames.entries()) {
    const sqlPath = join(MIGRATIONS_DIR, name, "migration.sql");
    const id = `mig${i}`;
    importLines.push(
      `import ${id} from ${JSON.stringify(toImportPath(outPath, sqlPath))} with { type: "file" };`,
    );
    migEntries.push(`  { name: ${JSON.stringify(name)}, path: ${id} },`);
  }

  for (const [i, rel] of webRels.entries()) {
    const filePath = join(WEB_DIST_DIR, rel);
    const id = `web${i}`;
    importLines.push(
      `import ${id} from ${JSON.stringify(toImportPath(outPath, filePath))} with { type: "file" };`,
    );
    webEntries.push(`  { rel: ${JSON.stringify(rel)}, path: ${id} },`);
  }

  const source = `/** AUTO-GENERATED by scripts/gen-standalone-compile-entry.ts — do not edit */
import { registerEmbeddedMigrations } from ${JSON.stringify(migRegisterImport)};
import { registerEmbeddedWebDist } from ${JSON.stringify(webRegisterImport)};
${importLines.join("\n")}

registerEmbeddedMigrations([
${migEntries.join("\n")}
]);

registerEmbeddedWebDist([
${webEntries.join("\n")}
]);

await import(${JSON.stringify(cliImport)});
`;

  writeFileSync(outPath, source);
  console.log(
    `wrote ${outPath} (${migrationNames.length} migrations, ${webRels.length} web files embedded)`,
  );
}

main();
