/** GENERATED by scripts/gen-shared-shapes — do not edit by hand. */
import { z } from "zod";
import { messagePayloadSchema } from "../jsonb/message-payload.ts";

export const messageSelectSchema = z.object({
  /** Globally unique row id (PG PK; compression points to pos, not this column) */
  id: z.string(),
  conversation_id: z.string(),
  subject_id: z.number(),
  /** Monotonic in-conversation sequence (compression l2/l3 point here; domain Message.pos) */
  pos: z.number(),
  payload: messagePayloadSchema,
});

export const messageInsertSchema = z.object({
  /** Globally unique row id (PG PK; compression points to pos, not this column) */
  id: z.string(),
  conversation_id: z.string(),
  subject_id: z.number(),
  /** Monotonic in-conversation sequence (compression l2/l3 point here; domain Message.pos) */
  pos: z.number(),
  payload: messagePayloadSchema,
});

export type MessageSelect = z.infer<typeof messageSelectSchema>;
export type MessageInsert = z.infer<typeof messageInsertSchema>;
