/** GENERATED by scripts/gen-shared-shapes — do not edit by hand. */
import { z } from "zod";
import { selfBlockKeySchema } from "../entity/enums.ts";

export const selfBlocksSelectSchema = z.object({
  /** Self-layer five blocks (one row per block_key) */
  block_key: selfBlockKeySchema,
  content: z.string(),
  locked: z.boolean(),
  version: z.number(),
  updated_by: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
});

export const selfBlocksInsertSchema = z.object({
  /** Self-layer five blocks (one row per block_key) */
  block_key: selfBlockKeySchema,
  content: z.string().optional(),
  locked: z.boolean().optional(),
  version: z.number().optional(),
  updated_by: z.string().nullable().optional(),
  created_at: z.coerce.date().optional(),
  updated_at: z.coerce.date().optional(),
});

export type SelfBlocksSelect = z.infer<typeof selfBlocksSelectSchema>;
export type SelfBlocksInsert = z.infer<typeof selfBlocksInsertSchema>;
