export {
  companionModelEntrySchema,
  companionMotionEntrySchema,
  companionBehaviorSchema,
  companionMotionSlotsSchema,
  companionConfigSchema,
  DEFAULT_COMPANION_BEHAVIOR,
  emptyCompanionMotionSlots,
  defaultCompanionRuntimeConfig,
  nextCompanionSort,
  sortCompanionEntries,
  companionModelCacheFileName,
  companionMotionCacheFileName,
  companionModelCachePath,
  companionMotionCachePath,
  type CompanionRuntimeConfig,
  type CompanionModelEntry,
  type CompanionMotionEntry,
} from "@freeanima/shared/companion-config";
