import type { HabitPreset } from "./types.ts";

/** 内置习惯库（静态；对标滴答常见预设） */
export const HABIT_PRESETS: HabitPreset[] = [
  {
    key: "drink_water",
    title: "喝水",
    polarity: "build",
    record_mode: "auto",
    target: 8,
    unit: "杯",
    auto_amount: 1,
    day_section: "morning",
    icon: "💧",
  },
  {
    key: "breakfast",
    title: "吃早餐",
    polarity: "build",
    record_mode: "boolean",
    target: 1,
    unit: null,
    auto_amount: null,
    day_section: "morning",
    icon: "🍳",
  },
  {
    key: "fruit",
    title: "吃水果",
    polarity: "build",
    record_mode: "boolean",
    target: 1,
    unit: null,
    auto_amount: null,
    day_section: "afternoon",
    icon: "🍎",
  },
  {
    key: "early_rise",
    title: "早起",
    polarity: "build",
    record_mode: "boolean",
    target: 1,
    unit: null,
    auto_amount: null,
    day_section: "morning",
    icon: "🌅",
  },
  {
    key: "early_sleep",
    title: "早睡",
    polarity: "build",
    record_mode: "boolean",
    target: 1,
    unit: null,
    auto_amount: null,
    day_section: "evening",
    icon: "🌙",
  },
  {
    key: "words",
    title: "背单词",
    polarity: "build",
    record_mode: "manual",
    target: 50,
    unit: "个",
    auto_amount: null,
    day_section: "morning",
    icon: "📚",
  },
  {
    key: "read",
    title: "阅读",
    polarity: "build",
    record_mode: "manual",
    target: 30,
    unit: "分钟",
    auto_amount: null,
    day_section: "evening",
    icon: "📖",
  },
  {
    key: "no_snacks",
    title: "戒零食",
    polarity: "break",
    record_mode: "boolean",
    target: 0,
    unit: null,
    auto_amount: null,
    day_section: "other",
    icon: "🚫",
  },
  {
    key: "exercise",
    title: "锻炼身体",
    polarity: "build",
    record_mode: "boolean",
    target: 1,
    unit: null,
    auto_amount: null,
    day_section: "afternoon",
    icon: "🏃",
  },
  {
    key: "meditate",
    title: "冥想",
    polarity: "build",
    record_mode: "auto",
    target: 10,
    unit: "分钟",
    auto_amount: 10,
    day_section: "morning",
    icon: "🧘",
  },
  {
    key: "no_anger",
    title: "不发脾气",
    polarity: "break",
    record_mode: "boolean",
    target: 0,
    unit: null,
    auto_amount: null,
    day_section: "other",
    icon: "😌",
  },
  {
    key: "progress",
    title: "每天进步一点点",
    polarity: "build",
    record_mode: "boolean",
    target: 1,
    unit: null,
    auto_amount: null,
    day_section: "other",
    icon: "✨",
  },
];

export function listHabitPresets(): HabitPreset[] {
  return HABIT_PRESETS;
}
